"""Adaptive Learning Tutor — an AI-driven adaptive learning app.

Flow:
    1. Subject-selection landing page.
    2. Once a subject is chosen, the adaptive quiz dashboard takes over, loading
       that subject's curriculum dynamically.

Questions are generated by a Llama 3 model; difficulty adapts to performance.

LLM backend (auto-detected):
    - Local dev → Ollama (`ollama serve` + `ollama pull llama3`).
    - Cloud     → Groq's free Llama 3 API. Set GROQ_API_KEY (Streamlit secret or
                  env var) and the app uses Groq automatically.

Run locally:
    streamlit run app.py
"""

import json
import os

import streamlit as st

try:  # Optional locally; only needed for the Ollama backend.
    import ollama
except ImportError:  # pragma: no cover
    ollama = None

# --------------------------------------------------------------------------- #
# Curriculum data structure — keyed by subject, then chapter, then tier.
# --------------------------------------------------------------------------- #
# Ordered difficulty tiers (shared across all subjects).
TIERS = ["Novice", "Intermediate", "Expert"]

# Each subject maps to an ORDERED dict of chapters (Python 3.7+ preserves
# insertion order), and each chapter carries per-tier guidance handed to the
# model so generated questions sit at the right conceptual level.
SUBJECTS = {
    "Basic Python Programming": {
        "Chapter 1: Variables & Data Types": {
            "Novice": (
                "Recognising variables, basic assignment, and the core built-in "
                "types (int, float, str, bool). Reading simple values."
            ),
            "Intermediate": (
                "Type conversion/casting, string formatting (f-strings), and "
                "predicting the type or value of simple expressions."
            ),
            "Expert": (
                "Mutability vs immutability, reference semantics, truthiness, "
                "and subtle coercion/edge cases (int vs float division, None)."
            ),
        },
        "Chapter 2: Conditionals & Loops": {
            "Novice": (
                "Basic if/else, comparison operators, and simple for/while "
                "loops over ranges or lists."
            ),
            "Intermediate": (
                "elif chains, nested loops, break/continue, and tracing the "
                "output of a short loop."
            ),
            "Expert": (
                "Loop/else clauses, off-by-one reasoning, short-circuit "
                "evaluation, and comprehensions vs explicit loops."
            ),
        },
        "Chapter 3: Functions": {
            "Novice": (
                "Defining and calling functions, parameters, and return values."
            ),
            "Intermediate": (
                "Default arguments, keyword vs positional args, and variable "
                "scope (local vs global)."
            ),
            "Expert": (
                "*args/**kwargs, mutable default-argument pitfalls, closures, "
                "and first-class/higher-order functions."
            ),
        },
    },
    "Data Structures & Algorithms": {
        "Chapter 1: Arrays & Linked Lists": {
            "Novice": (
                "What arrays/lists are, indexing, and basic append/insert/"
                "remove operations."
            ),
            "Intermediate": (
                "Time complexity of common list operations, and singly vs "
                "doubly linked lists."
            ),
            "Expert": (
                "Amortised analysis of dynamic arrays, cache locality, and "
                "pointer manipulation edge cases in linked lists."
            ),
        },
        "Chapter 2: Stacks, Queues & Hashing": {
            "Novice": (
                "LIFO vs FIFO concepts, basic push/pop/enqueue/dequeue, and "
                "what a hash map stores."
            ),
            "Intermediate": (
                "Implementing stacks/queues with arrays or linked lists, and "
                "hash collisions and load factor."
            ),
            "Expert": (
                "Open addressing vs chaining, deque internals, and designing "
                "O(1) operations under constraints."
            ),
        },
        "Chapter 3: Sorting & Searching": {
            "Novice": (
                "Linear vs binary search, and the idea of sorting a list."
            ),
            "Intermediate": (
                "Big-O of bubble/insertion/merge/quick sort, and binary search "
                "preconditions."
            ),
            "Expert": (
                "Stability, in-place vs extra-space trade-offs, worst-case "
                "pivots, and lower bounds on comparison sorting."
            ),
        },
    },
    "Intro to Data Science": {
        "Chapter 1: Data & Statistics Basics": {
            "Novice": (
                "Mean, median, mode, and the difference between categorical and "
                "numerical data."
            ),
            "Intermediate": (
                "Variance/standard deviation, distributions, and interpreting "
                "correlation."
            ),
            "Expert": (
                "Sampling bias, confidence intervals, and correlation vs "
                "causation pitfalls."
            ),
        },
        "Chapter 2: Data Wrangling with Pandas": {
            "Novice": (
                "What a DataFrame is, selecting columns/rows, and reading a CSV."
            ),
            "Intermediate": (
                "Filtering, groupby/aggregation, and handling missing values."
            ),
            "Expert": (
                "Merges/joins, reshaping (pivot/melt), and vectorisation vs "
                "apply performance."
            ),
        },
        "Chapter 3: Visualization & Intro to ML": {
            "Novice": (
                "Choosing the right chart (bar/line/scatter) and reading a plot."
            ),
            "Intermediate": (
                "Train/test split, what supervised learning is, and over/under-"
                "fitting intuition."
            ),
            "Expert": (
                "Bias-variance trade-off, evaluation metrics (precision/recall/"
                "ROC), and cross-validation."
            ),
        },
    },
}

# Short blurbs shown on the landing page.
SUBJECT_BLURBS = {
    "Basic Python Programming": "Variables, control flow, and functions.",
    "Data Structures & Algorithms": "Arrays, hashing, sorting, and complexity.",
    "Intro to Data Science": "Statistics, pandas, and a first taste of ML.",
}

PROMOTION_THRESHOLD = 2  # consecutive correct answers needed to level up

# Default model per backend.
OLLAMA_MODEL = "llama3"
GROQ_MODEL = "llama-3.1-8b-instant"
GROQ_BASE_URL = "https://api.groq.com/openai/v1"


def _config(key, default=None):
    """Read a config value from Streamlit secrets (cloud) or env (local)."""
    try:
        if key in st.secrets:
            return st.secrets[key]
    except Exception:  # noqa: BLE001 — no secrets file in local dev is fine
        pass
    return os.environ.get(key, default)


def resolve_backend():
    """Pick the LLM backend. Groq if an API key is present, else local Ollama.

    Returns a dict: {name: 'groq'|'ollama', model: str, api_key: str|None}.
    """
    api_key = _config("GROQ_API_KEY")
    forced = (_config("LLM_BACKEND") or "").strip().lower()
    use_groq = forced == "groq" or (forced != "ollama" and bool(api_key))
    if use_groq:
        return {"name": "groq", "model": _config("LLM_MODEL", GROQ_MODEL),
                "api_key": api_key}
    return {"name": "ollama", "model": _config("LLM_MODEL", OLLAMA_MODEL),
            "api_key": None}


def chapters_for(subject):
    """Ordered list of chapter names for a subject ([] if none/unknown)."""
    return list(SUBJECTS.get(subject, {}).keys())


# --------------------------------------------------------------------------- #
# Ollama integration
# --------------------------------------------------------------------------- #
def list_local_models():
    """Return the list of model names available locally (raises on no server)."""
    data = ollama.list()
    models = getattr(data, "models", None)
    if models is None and isinstance(data, dict):
        models = data.get("models", [])
    names = []
    for m in models or []:
        name = getattr(m, "model", None)
        if name is None and isinstance(m, dict):
            name = m.get("model") or m.get("name")
        if name:
            names.append(name)
    return names


def model_is_available(model, names):
    """True if `model` matches a locally pulled model (with or without a tag)."""
    base = model.split(":")[0]
    return any(n == model or n.split(":")[0] == base for n in names)


def _ollama_chat(backend, messages, temperature):
    if ollama is None:
        raise RuntimeError("The 'ollama' package is not installed.")
    resp = ollama.chat(
        model=backend["model"],
        messages=messages,
        format="json",
        options={"temperature": temperature},
    )
    return resp["message"]["content"]


def _groq_chat(backend, messages, temperature):
    # Groq is OpenAI-compatible, so we reuse the openai client with its base URL.
    from openai import OpenAI

    client = OpenAI(api_key=backend["api_key"], base_url=GROQ_BASE_URL)
    resp = client.chat.completions.create(
        model=backend["model"],
        messages=messages,
        temperature=temperature,
        response_format={"type": "json_object"},
    )
    return resp.choices[0].message.content


def _chat_json(system_prompt, user_prompt, temperature=0.6, retries=2):
    """Call the active backend in JSON mode and return the parsed dict.

    Retries a few times if the model emits invalid JSON.
    """
    backend = st.session_state.backend
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]
    call = _groq_chat if backend["name"] == "groq" else _ollama_chat
    last_err = None
    for _ in range(retries + 1):
        content = call(backend, messages, temperature)
        try:
            return json.loads(content)
        except (json.JSONDecodeError, TypeError) as exc:
            last_err = exc
    raise ValueError(f"Model did not return valid JSON after retries: {last_err}")


def generate_adaptive_question(subject, chapter, difficulty):
    """Generate a multiple-choice question tuned to subject, chapter, and tier.

    Returns a dict: {question, options{A..D}, correct_option, explanation}.
    """
    tier_desc = SUBJECTS[subject][chapter][difficulty]
    system_prompt = (
        "You are an expert instructor writing a single high-quality "
        "multiple-choice question. Respond ONLY with JSON. Do not include "
        "markdown fences or any prose outside the JSON object."
    )
    user_prompt = f"""Create one {difficulty}-level multiple-choice question for the topic "{chapter}" in a "{subject}" course.

Difficulty guidance: {tier_desc}

Requirements:
- Exactly four answer options labelled A, B, C, D.
- Exactly one correct option.
- A concise explanation of why the correct answer is right.

Return JSON with EXACTLY this shape:
{{"question": "the question text", "options": {{"A": "...", "B": "...", "C": "...", "D": "..."}}, "correct_option": "A", "explanation": "why the correct answer is correct"}}

The value of correct_option MUST be one of: A, B, C, D."""

    data = _chat_json(system_prompt, user_prompt, temperature=0.7)

    required = ("question", "options", "correct_option", "explanation")
    if not all(k in data for k in required):
        raise ValueError(f"Question JSON missing keys. Got: {list(data)}")
    if not isinstance(data["options"], dict) or set(data["options"]) < set("ABCD"):
        raise ValueError("Question options must include keys A, B, C, D.")
    if data["correct_option"] not in data["options"]:
        raise ValueError("correct_option does not match any provided option.")
    return data


def evaluate_open_response(question, student_answer):
    """Grade a free-text answer with the model.

    Returns a dict: {is_correct: bool, confidence: int(0-100), feedback: str}.
    """
    system_prompt = (
        "You are a fair, encouraging tutor grading a student's free-text "
        "answer. Be rigorous about correctness but supportive in tone. Respond "
        "ONLY with JSON, no markdown fences or extra prose."
    )
    user_prompt = f"""Question: {question}

Student's answer: {student_answer}

Evaluate whether the student's answer is correct. Provide constructive feedback
that explains the correct reasoning regardless of whether they were right.

Return JSON with EXACTLY this shape:
{{"is_correct": true, "confidence": 85, "feedback": "constructive feedback and the correct explanation"}}

- is_correct: boolean.
- confidence: integer 0-100, your confidence in this evaluation.
- feedback: 1-3 sentences."""

    data = _chat_json(system_prompt, user_prompt, temperature=0.2)
    return {
        "is_correct": bool(data.get("is_correct", False)),
        "confidence": int(data.get("confidence", 0)),
        "feedback": str(data.get("feedback", "No feedback returned.")),
    }


# --------------------------------------------------------------------------- #
# Session state
# --------------------------------------------------------------------------- #
def init_state():
    defaults = {
        "backend": resolve_backend(),
        "selected_subject": None,   # None => show landing page
        "current_chapter": None,    # set when a subject is chosen
        "current_difficulty": TIERS[0],
        "consecutive_correct": 0,
        "history": [],
        "current_question": None,
        "last_result": None,
        "answer_mode": "Multiple choice",
        "completed": False,
        "total_answered": 0,
        "total_correct": 0,
    }
    for key, value in defaults.items():
        st.session_state.setdefault(key, value)


def reset_progress():
    """Reset all per-run progress, keeping the currently selected subject."""
    subject = st.session_state.get("selected_subject")
    chapters = chapters_for(subject)
    st.session_state.current_chapter = chapters[0] if chapters else None
    st.session_state.current_difficulty = TIERS[0]
    st.session_state.consecutive_correct = 0
    st.session_state.history = []
    st.session_state.current_question = None
    st.session_state.last_result = None
    st.session_state.completed = False
    st.session_state.total_answered = 0
    st.session_state.total_correct = 0
    st.session_state.pop("open_answer", None)


def start_subject(subject):
    """Lock in a subject and initialise a fresh learning session for it."""
    st.session_state.selected_subject = subject
    reset_progress()  # picks up the new subject's first chapter


def change_subject():
    """Return to the landing page, clearing the current session."""
    st.session_state.selected_subject = None
    reset_progress()


# --------------------------------------------------------------------------- #
# Adaptivity logic
# --------------------------------------------------------------------------- #
def _promote():
    """Move up a tier; graduate to the next chapter (or finish) at the top."""
    chapters = chapters_for(st.session_state.selected_subject)
    tier_idx = TIERS.index(st.session_state.current_difficulty)
    if tier_idx < len(TIERS) - 1:
        st.session_state.current_difficulty = TIERS[tier_idx + 1]
        return f"🎉 Two in a row! Promoted to **{st.session_state.current_difficulty}** tier."

    chap_idx = chapters.index(st.session_state.current_chapter)
    if chap_idx < len(chapters) - 1:
        st.session_state.current_chapter = chapters[chap_idx + 1]
        st.session_state.current_difficulty = TIERS[0]
        return f"🏆 Chapter mastered! Advancing to **{st.session_state.current_chapter}** at Novice."

    st.session_state.completed = True
    return "🎓 You've mastered every chapter. Subject complete!"


def _demote():
    """Drop one tier to reinforce foundations (no-op at Novice)."""
    tier_idx = TIERS.index(st.session_state.current_difficulty)
    if tier_idx > 0:
        st.session_state.current_difficulty = TIERS[tier_idx - 1]
        return f"↩️ Let's reinforce the basics — back to **{st.session_state.current_difficulty}** tier."
    return "💪 Staying at Novice to build a solid foundation. Keep going!"


def apply_result(correct):
    """Update streak/difficulty/chapter based on a graded answer."""
    st.session_state.total_answered += 1
    if correct:
        st.session_state.total_correct += 1
        st.session_state.consecutive_correct += 1
        if st.session_state.consecutive_correct >= PROMOTION_THRESHOLD:
            st.session_state.consecutive_correct = 0
            return _promote()
        remaining = PROMOTION_THRESHOLD - st.session_state.consecutive_correct
        return f"✅ Correct! {remaining} more in a row to level up."
    st.session_state.consecutive_correct = 0
    return _demote()


def render_llm_error(exc):
    """Friendly error panel for connection / model problems."""
    backend = st.session_state.backend
    if backend["name"] == "groq":
        st.error(
            "**Couldn't reach the Groq API.** Check that:\n\n"
            "1. `GROQ_API_KEY` is set (Streamlit secret or env var).\n"
            f"2. The model `{backend['model']}` is valid and your key has quota.\n\n"
            f"Details: `{exc}`"
        )
    else:
        st.error(
            "**Couldn't reach the local model.** Check that everything is set up:"
            "\n\n1. Start the server:  `ollama serve`\n"
            f"2. Pull the model:  `ollama pull {backend['model']}`\n\n"
            f"Details: `{exc}`"
        )


# --------------------------------------------------------------------------- #
# App
# --------------------------------------------------------------------------- #
st.set_page_config(page_title="Adaptive Tutor", page_icon="🧠")
init_state()

# =========================================================================== #
# LANDING PAGE — shown until a subject is selected.
# =========================================================================== #
if st.session_state.selected_subject is None:
    st.title("🧠 Adaptive Tutor")
    st.markdown("## Which subject do you want to master today?")
    st.caption("Pick a track — your tutor will adapt the difficulty as you go.")
    st.write("")

    subject = st.radio(
        "Available subjects",
        options=list(SUBJECTS.keys()),
        format_func=lambda s: f"{s} — {SUBJECT_BLURBS.get(s, '')}",
        label_visibility="collapsed",
    )

    st.write("")
    if st.button("🚀 Start Learning", type="primary", use_container_width=True):
        start_subject(subject)
        st.rerun()

    st.stop()

# =========================================================================== #
# MAIN DASHBOARD — a subject is selected.
# =========================================================================== #
subject = st.session_state.selected_subject

st.title("🧠 Adaptive Tutor")
st.caption(f"**{subject}** · powered by a local model via Ollama")

# --- Sidebar: stats + settings ------------------------------------------------
with st.sidebar:
    st.header("📚 Subject")
    st.markdown(f"**{subject}**")
    if st.button("🔁 Change Subject", use_container_width=True):
        change_subject()
        st.rerun()

    st.divider()
    st.header("📊 Your Stats")
    st.metric("Current Chapter", st.session_state.current_chapter.split(":")[0])
    st.caption(st.session_state.current_chapter.split(":", 1)[1].strip())
    st.metric("Mastery Tier", st.session_state.current_difficulty)
    st.metric("🔥 Streak", f"{st.session_state.consecutive_correct} / {PROMOTION_THRESHOLD}")

    if st.session_state.total_answered:
        acc = 100 * st.session_state.total_correct / st.session_state.total_answered
        st.caption(
            f"Answered **{st.session_state.total_answered}** · "
            f"Accuracy **{acc:.0f}%**"
        )

    st.divider()
    st.subheader("⚙️ Settings")
    _b = st.session_state.backend
    st.caption(f"LLM backend: **{_b['name']}** · model `{_b['model']}`")
    st.session_state.answer_mode = st.radio(
        "Answer mode",
        ["Multiple choice", "Open-ended (AI-graded)"],
        index=0 if st.session_state.answer_mode == "Multiple choice" else 1,
        help="Multiple choice is graded locally. Open-ended is graded by the model.",
    )

    if st.button("🔄 Reset progress", use_container_width=True):
        reset_progress()
        st.rerun()

    st.divider()
    with st.expander(f"📜 History ({len(st.session_state.history)})"):
        if not st.session_state.history:
            st.caption("No answers yet.")
        for h in reversed(st.session_state.history):
            mark = "✅" if h["correct"] else "❌"
            st.markdown(
                f"{mark} **{h['chapter'].split(':')[0]} · {h['difficulty']}**  \n"
                f"<span style='font-size:0.85em'>{h['question'][:90]}…</span>",
                unsafe_allow_html=True,
            )

# --- Subject-complete screen --------------------------------------------------
if st.session_state.completed:
    st.balloons()
    st.success(f"🎓 **Congratulations — you've completed {subject}!**")
    acc = (
        100 * st.session_state.total_correct / st.session_state.total_answered
        if st.session_state.total_answered
        else 0
    )
    st.write(
        f"You answered **{st.session_state.total_answered}** questions with "
        f"**{acc:.0f}%** accuracy across all three chapters."
    )
    col1, col2 = st.columns(2)
    with col1:
        if st.button("🔁 Pick another subject", use_container_width=True):
            change_subject()
            st.rerun()
    with col2:
        if st.button("↺ Retake this subject", use_container_width=True):
            reset_progress()
            st.rerun()
    st.stop()

# --- Pre-flight: verify the active backend before generating ------------------
_backend = st.session_state.backend
if _backend["name"] == "groq":
    if not _backend["api_key"]:
        st.error(
            "**No `GROQ_API_KEY` configured.** Add it to Streamlit secrets "
            "(cloud) or as an environment variable (local), then reload."
        )
        st.stop()
else:  # ollama — verify the server is up and the model is pulled
    try:
        local_models = list_local_models()
    except Exception as exc:  # noqa: BLE001
        render_llm_error(exc)
        if st.button("Retry connection"):
            st.rerun()
        st.stop()

    if not model_is_available(_backend["model"], local_models):
        st.warning(
            f"Model **{_backend['model']}** isn't pulled yet. Run "
            f"`ollama pull {_backend['model']}` (available locally: "
            f"{', '.join(local_models) or 'none'})."
        )
        if st.button("Retry"):
            st.rerun()
        st.stop()

# --- Generate a question if we don't have an active one -----------------------
if st.session_state.current_question is None:
    with st.spinner(
        f"Generating a {st.session_state.current_difficulty} question for "
        f"{st.session_state.current_chapter.split(':')[0]}…"
    ):
        try:
            st.session_state.current_question = generate_adaptive_question(
                subject,
                st.session_state.current_chapter,
                st.session_state.current_difficulty,
            )
        except Exception as exc:  # noqa: BLE001
            render_llm_error(exc)
            if st.button("Try again"):
                st.rerun()
            st.stop()

question = st.session_state.current_question

# --- Question + answer area ---------------------------------------------------
st.subheader(
    f"{st.session_state.current_chapter.split(':')[0]} · "
    f"{st.session_state.current_difficulty}"
)
st.markdown(f"### {question['question']}")

# Phase 1: awaiting an answer.
if st.session_state.last_result is None:
    if st.session_state.answer_mode == "Multiple choice":
        choice = st.radio(
            "Choose your answer:",
            options=list("ABCD"),
            format_func=lambda k: f"{k}.  {question['options'][k]}",
            index=None,
        )
        if st.button("Submit answer", type="primary"):
            if choice is None:
                st.warning("Pick an option first.")
            else:
                correct = choice == question["correct_option"]
                transition = apply_result(correct)
                st.session_state.history.append({
                    "chapter": st.session_state.current_chapter,
                    "difficulty": st.session_state.current_difficulty,
                    "question": question["question"],
                    "correct": correct,
                })
                st.session_state.last_result = {
                    "correct": correct,
                    "your_answer": f"{choice}. {question['options'][choice]}",
                    "correct_answer": (
                        f"{question['correct_option']}. "
                        f"{question['options'][question['correct_option']]}"
                    ),
                    "feedback": question["explanation"],
                    "transition": transition,
                    "confidence": None,
                }
                st.rerun()

    else:  # Open-ended, AI-graded
        answer = st.text_area("Type your answer:", height=120, key="open_answer")
        if st.button("Submit answer", type="primary"):
            if not answer.strip():
                st.warning("Write an answer first.")
            else:
                with st.spinner("Grading your answer…"):
                    try:
                        evaluation = evaluate_open_response(
                            question["question"], answer
                        )
                    except Exception as exc:  # noqa: BLE001
                        render_llm_error(exc)
                        st.stop()
                correct = evaluation["is_correct"]
                transition = apply_result(correct)
                st.session_state.history.append({
                    "chapter": st.session_state.current_chapter,
                    "difficulty": st.session_state.current_difficulty,
                    "question": question["question"],
                    "correct": correct,
                })
                st.session_state.last_result = {
                    "correct": correct,
                    "your_answer": answer,
                    "correct_answer": None,
                    "feedback": evaluation["feedback"],
                    "transition": transition,
                    "confidence": evaluation["confidence"],
                }
                st.rerun()

# Phase 2: show feedback, offer the next question.
else:
    result = st.session_state.last_result
    if result["correct"]:
        st.success("✅ Correct!")
    else:
        st.error("❌ Not quite.")

    st.markdown(f"**Your answer:** {result['your_answer']}")
    if result["correct_answer"]:
        st.markdown(f"**Correct answer:** {result['correct_answer']}")
    if result["confidence"] is not None:
        st.caption(f"Grader confidence: {result['confidence']}%")

    st.info(f"**Feedback:** {result['feedback']}")
    st.markdown(f"*{result['transition']}*")

    if st.button("Next question ➡️", type="primary"):
        st.session_state.current_question = None
        st.session_state.last_result = None
        st.session_state.pop("open_answer", None)
        st.rerun()
