"""Adaptive Tutor — a K-12 family learning adventure.

Outcome-driven design for kids (Kindergarten → Middle School):
  • PARENT picks grade-band GOALS (learning adventures). A curriculum map turns
    each goal into age-appropriate modules that become the child's quest path.
  • STUDENT plays a kid-friendly adaptive loop (WARM-UP → STORY → PUZZLE) with
    difficulty that gently self-adjusts to performance.

Content is generated by a Llama 3 model in an encouraging, gamified, story-driven
voice. Backend auto-detects:
  • Local dev → Ollama (`ollama serve` + `ollama pull llama3`), the default.
  • Cloud     → Groq's free Llama 3 API when GROQ_API_KEY is set.

Run locally:  streamlit run app.py
"""

import json
import os

import streamlit as st

try:  # Optional locally; only needed for the Ollama backend.
    import ollama
except ImportError:  # pragma: no cover
    ollama = None

# =========================================================================== #
# Themes — injected conditionally on role (see bottom of file).
# =========================================================================== #
STUDENT_CSS = """
<style>
.stApp { background: radial-gradient(circle at 20% 0%, #16121f 0%, #0B0C10 60%); color:#C5C6C7; }
.stApp, .stMarkdown, p, span, label, li { color:#C5C6C7 !important; }
h1,h2,h3,h4 { color:#FF007F !important; letter-spacing:0.5px; }
h1 { text-shadow:0 0 16px rgba(255,0,127,0.6); }
a { color:#00E5FF !important; }
[data-testid="stSidebar"] { background:linear-gradient(180deg,#0e1117 0%,#241433 100%);
    border-right:1px solid rgba(255,0,127,0.3); }

.hud-card { background:#1F2833; border:1px solid rgba(255,0,127,0.35); border-radius:16px;
    padding:16px; margin-bottom:16px; box-shadow:0 0 18px rgba(255,0,127,0.16); }
.hud-title { color:#FF007F; font-weight:800; font-size:1.05rem; text-transform:uppercase;
    letter-spacing:1.5px; text-shadow:0 0 8px rgba(255,0,127,0.6); margin-bottom:10px; }
.profile-avatar { font-size:3.4rem; text-align:center; text-shadow:0 0 18px rgba(0,229,255,0.8);
    margin-bottom:2px; }
.profile-name { text-align:center; color:#00E5FF; font-weight:800; letter-spacing:1px;
    text-shadow:0 0 8px rgba(0,229,255,0.6); margin-bottom:8px; }
.hud-row { display:flex; justify-content:space-between; font-size:0.9rem; margin:4px 0; }
.hud-row .k { color:#7f8c8d; } .hud-row .v { color:#C5C6C7; font-weight:700; }
.xp-bar { width:100%; height:18px; background:#0B0C10; border-radius:10px;
    border:1px solid rgba(0,229,255,0.4); overflow:hidden; margin:6px 0; }
.xp-fill { height:100%; background:linear-gradient(90deg,#00E5FF,#FF007F);
    box-shadow:0 0 12px rgba(255,0,127,0.8); transition:width 0.5s ease; }
.xp-text { font-size:0.78rem; color:#7f8c8d; text-align:right; }
.streak-meter { text-align:center; font-size:1.1rem; font-weight:800; color:#FFB300;
    text-shadow:0 0 10px rgba(255,179,0,0.7); margin:6px 0; }
.badge { display:inline-block; margin:4px 4px 0 0; padding:6px 11px; background:#0B0C10;
    border:1px solid #FF007F; border-radius:20px; font-size:0.74rem; color:#FF007F;
    font-weight:700; box-shadow:0 0 8px rgba(255,0,127,0.45); }
.badge-empty { font-size:0.78rem; color:#566573; font-style:italic; }
[data-testid="stVerticalBlockBorderWrapper"] { background:#1F2833;
    border:1px solid rgba(0,229,255,0.30) !important; border-radius:18px !important;
    box-shadow:0 0 22px rgba(0,229,255,0.12); padding:6px 4px; }
code, pre { background:#0B0C10 !important; border:1px solid rgba(0,229,255,0.25); }
.mission-card { background:#1F2833; border:1px solid rgba(0,229,255,0.30); border-radius:18px;
    padding:18px; min-height:104px; box-shadow:0 0 18px rgba(0,229,255,0.12); }
.mission-card .title { color:#00E5FF; font-weight:800; font-size:1.05rem; }
.mission-card .blurb { color:#9aa0a6; font-size:0.85rem; margin-top:6px; }
.stButton > button { background:#0B0C10; color:#FF007F !important; border:2px solid #FF007F;
    border-radius:14px; font-weight:800; letter-spacing:0.6px; padding:0.55rem 1rem;
    transition:all 0.2s ease-in-out; box-shadow:0 0 10px rgba(255,0,127,0.4); }
.stButton > button:hover { color:#0B0C10 !important; background:#FF007F;
    transform:translateY(-2px) scale(1.03);
    box-shadow:0 0 22px rgba(255,0,127,0.95), 0 0 40px rgba(255,0,127,0.5); }
.stButton > button[kind="primary"] { border-color:#00E5FF; color:#00E5FF !important;
    box-shadow:0 0 12px rgba(0,229,255,0.6); animation:pulse 1.8s infinite; }
.stButton > button[kind="primary"]:hover { background:#00E5FF; color:#0B0C10 !important; }
@keyframes pulse { 0%{box-shadow:0 0 8px rgba(0,229,255,0.5);}
    50%{box-shadow:0 0 22px rgba(0,229,255,0.95);} 100%{box-shadow:0 0 8px rgba(0,229,255,0.5);} }
[data-testid="stRadio"] label { color:#C5C6C7 !important; }
.mastery-meter { text-align:center; font-weight:800; color:#00E5FF; font-size:1.05rem;
    text-shadow:0 0 12px rgba(0,229,255,0.8); margin:6px 0; }
.path-row { line-height:2.1; font-size:0.82rem; }
.node { display:inline-block; padding:3px 9px; margin:2px; border-radius:8px; background:#0B0C10;
    border:1px solid #2b3340; color:#9aa0a6; }
.node-active { border-color:#00E5FF; color:#00E5FF; font-weight:700;
    box-shadow:0 0 10px rgba(0,229,255,0.6); }
.node-new { border-color:#FF007F; color:#FF007F; font-weight:700;
    box-shadow:0 0 12px rgba(255,0,127,0.75); }
</style>
"""

PARENT_CSS = """
<style>
.stApp { background:#F4F6F9; color:#1A202C; }
.stApp, .stMarkdown, p, span, label, li { color:#1A202C !important; }
h1,h2,h3,h4 { color:#1E3A8A !important; letter-spacing:0; text-shadow:none !important; }
a { color:#1E3A8A !important; }
[data-testid="stSidebar"] { background:#FFFFFF; border-right:1px solid #E2E8F0;
    box-shadow:2px 0 8px rgba(0,0,0,0.04); }
.hud-card, .parent-card { background:#FFFFFF; border:1px solid #E2E8F0; border-radius:12px;
    padding:16px; margin-bottom:16px; box-shadow:0 1px 4px rgba(0,0,0,0.08); }
.hud-title { color:#1E3A8A; font-weight:700; font-size:1.0rem; text-transform:uppercase;
    letter-spacing:1px; text-shadow:none; margin-bottom:10px; }
.profile-avatar { font-size:2.6rem; text-align:center; margin-bottom:2px; }
.profile-name { text-align:center; color:#1E3A8A; font-weight:700; margin-bottom:8px; }
.hud-row { display:flex; justify-content:space-between; font-size:0.9rem; margin:4px 0; }
.hud-row .k { color:#64748B; } .hud-row .v { color:#1A202C; font-weight:700; }
.xp-bar { width:100%; height:14px; background:#E2E8F0; border-radius:8px; overflow:hidden; margin:6px 0; }
.xp-fill { height:100%; background:linear-gradient(90deg,#1E3A8A,#3B82F6); transition:width 0.5s ease; }
.xp-text { font-size:0.78rem; color:#64748B; text-align:right; }
.streak-meter { text-align:center; font-weight:700; color:#B45309; margin:6px 0; }
.badge { display:inline-block; margin:4px 4px 0 0; padding:5px 10px; background:#EFF4FF;
    border:1px solid #3B82F6; border-radius:20px; font-size:0.72rem; color:#1E3A8A; font-weight:700; }
.badge-empty { font-size:0.78rem; color:#94A3B8; font-style:italic; }
.tile-row { display:flex; gap:12px; flex-wrap:wrap; }
.stat-tile { flex:1; min-width:100px; background:#FFFFFF; border:1px solid #E2E8F0; border-radius:10px;
    padding:14px; text-align:center; box-shadow:0 1px 4px rgba(0,0,0,0.06); }
.stat-tile .num { color:#1E3A8A; font-size:1.6rem; font-weight:800; }
.stat-tile .lbl { color:#64748B; font-size:0.72rem; text-transform:uppercase; letter-spacing:1px; }
[data-testid="stVerticalBlockBorderWrapper"] { background:#FFFFFF; border:1px solid #E2E8F0 !important;
    border-radius:12px !important; box-shadow:0 1px 4px rgba(0,0,0,0.06); padding:6px 4px; }
code, pre { background:#F1F5F9 !important; border:1px solid #E2E8F0; color:#1A202C !important; }
.grow-card { background:#F0FDF4; border:1px solid #BBF7D0; border-left:4px solid #16A34A;
    border-radius:10px; padding:14px; margin-bottom:10px; }
.grow-card .topic { color:#166534; font-weight:800; }
.rec-card { background:#F8FAFF; border:1px solid #E2E8F0; border-left:4px solid #3B82F6;
    border-radius:10px; padding:16px; box-shadow:0 1px 4px rgba(0,0,0,0.06); margin-bottom:10px; }
.rec-card .tag { color:#1E3A8A; font-weight:800; text-transform:uppercase; letter-spacing:1px; font-size:0.8rem; }
.digest-card { background:#0F172A; border-radius:12px; padding:14px 18px; color:#E2E8F0;
    box-shadow:0 2px 10px rgba(0,0,0,0.15); }
.digest-card .hdr { color:#93C5FD; font-weight:800; letter-spacing:1px; }
.stButton > button { background:#FFFFFF; color:#1E3A8A !important; border:1px solid #3B82F6;
    border-radius:8px; font-weight:700; letter-spacing:0.3px; padding:0.5rem 1rem;
    transition:all 0.15s ease; box-shadow:0 1px 2px rgba(0,0,0,0.06); }
.stButton > button:hover { background:#3B82F6; color:#FFFFFF !important; transform:none;
    box-shadow:0 2px 6px rgba(30,58,138,0.25); }
.stButton > button[kind="primary"] { background:#1E3A8A; color:#FFFFFF !important;
    border:1px solid #1E3A8A; box-shadow:0 2px 6px rgba(30,58,138,0.25); animation:none; }
.stButton > button[kind="primary"]:hover { background:#3B82F6; border-color:#3B82F6; }
[data-baseweb="checkbox"] input { accent-color:#1E3A8A; }
[data-testid="stCheckbox"] svg { fill:#1E3A8A; }
[data-testid="stCheckbox"] label, [data-testid="stRadio"] label { color:#1A202C !important; }
.mastery-meter { text-align:center; font-weight:800; color:#1E3A8A; font-size:1.05rem; margin:6px 0; }
.path-row { line-height:2.1; font-size:0.82rem; }
.node { display:inline-block; padding:3px 9px; margin:2px; border-radius:8px; background:#F1F5F9;
    border:1px solid #E2E8F0; color:#475569; }
.node-active { border-color:#1E3A8A; color:#1E3A8A; font-weight:700; }
.node-new { border-color:#16A34A; color:#166534; background:#F0FDF4; font-weight:700; }
</style>
"""

# =========================================================================== #
# K-12 Curriculum — TRACK (grade band) → module → tier guidance for the model.
# (Internally named SUBJECTS so the engine helpers stay generic.)
# =========================================================================== #
TIERS = ["Novice", "Intermediate", "Expert"]
TIER_LABELS = {"Novice": "🌱 Explorer", "Intermediate": "⭐ Adventurer", "Expert": "🏆 Hero"}

SUBJECTS = {
    "Logic & Problem Solving": {  # K–2nd
        "Sequencing": {
            "Novice": "Putting 2-3 everyday steps in the right 1-2-3 order (like a morning routine).",
            "Intermediate": "Ordering 4-5 steps and spotting one step that is out of place.",
            "Expert": "Arranging longer sequences and fixing a jumbled-up order.",
        },
        "Shapes": {
            "Novice": "Naming basic shapes: circle, square, triangle, rectangle.",
            "Intermediate": "Counting sides and corners, and matching shapes that are alike.",
            "Expert": "Combining shapes and finding hidden shapes inside a picture.",
        },
        "Pattern Completion": {
            "Novice": "Finishing a simple AB color or shape pattern (red, blue, red, ...).",
            "Intermediate": "ABC patterns and growing patterns (1, 2, 3, ...).",
            "Expert": "Finding the rule of a pattern and predicting what comes next.",
        },
    },
    "Step-by-Step Thinking": {  # 3rd–5th
        "Conditional Logic Traps": {
            "Novice": "Simple if/then rules (if it rains, then take an umbrella).",
            "Intermediate": "if/else choices and avoiding one tricky 'gotcha' answer.",
            "Expert": "Nested if/then rules and spotting logic traps designed to fool you.",
        },
        "Loop Patterns": {
            "Novice": "Repeating one action a few times (repeat 3 times).",
            "Intermediate": "Figuring out how many loops are needed to reach a goal.",
            "Expert": "Loops inside loops and finding the shortest set of repeats.",
        },
        "Robot Commands": {
            "Novice": "Single move commands for a robot (forward, turn left, turn right).",
            "Intermediate": "Sequencing commands to guide a robot to a target square.",
            "Expert": "Debugging a list of commands to fix the robot's path.",
        },
    },
    "Creative Tech Foundations": {  # 6th–8th+
        "Variables": {
            "Novice": "A variable is a labeled box that stores a value (like score = 0).",
            "Intermediate": "Updating and changing variables, and simple expressions.",
            "Expert": "Using several variables together to track a game's score and state.",
        },
        "Basic Functions": {
            "Novice": "A function is a reusable action or 'spell' you can call by name.",
            "Intermediate": "Giving functions inputs (parameters) and getting outputs (return).",
            "Expert": "Combining functions together to build bigger behaviors.",
        },
        "Text-Adventure Game Building": {
            "Novice": "Branching story choices (go left or go right).",
            "Intermediate": "Tracking inventory/score with variables and if/else choices.",
            "Expert": "Combining loops, choices, and functions into a small playable game.",
        },
    },
}

# --------------------------------------------------------------------------- #
# Curriculum Map — parent GOALS (grade-band adventures) → modules.
# --------------------------------------------------------------------------- #
LOGIC = "Logic & Problem Solving"
STEPS = "Step-by-Step Thinking"
TECH = "Creative Tech Foundations"

GOALS = {
    LOGIC: {
        "icon": "🧩", "band": "K–2nd",
        "desc": "Sequencing, shapes, and patterns — building first problem-solving skills.",
        "modules": [(LOGIC, "Sequencing"), (LOGIC, "Shapes"), (LOGIC, "Pattern Completion")],
        "theme": "a colorful puzzle kingdom with friendly creatures",
    },
    STEPS: {
        "icon": "🤖", "band": "3rd–5th",
        "desc": "Conditionals, loops, and robot commands — thinking in clear steps.",
        "modules": [(STEPS, "Conditional Logic Traps"), (STEPS, "Loop Patterns"),
                    (STEPS, "Robot Commands")],
        "theme": "a robot command academy",
    },
    TECH: {
        "icon": "✨", "band": "6th–8th+",
        "desc": "Variables, functions, and building a text-adventure game.",
        "modules": [(TECH, "Variables"), (TECH, "Basic Functions"),
                    (TECH, "Text-Adventure Game Building")],
        "theme": "a space-coding adventure among the stars",
    },
}

# Kid-friendly profile avatars (emoji stands in for the avatar image).
AVATARS = [
    {"emoji": "🐱", "name": "Cyber Cat"},
    {"emoji": "🤖", "name": "Techno Knight"},
    {"emoji": "🚀", "name": "Astro Scout"},
    {"emoji": "🦊", "name": "Pixel Fox"},
    {"emoji": "🦖", "name": "Robo Dino"},
    {"emoji": "🧙", "name": "Star Mage"},
]
AVATAR_LABELS = [f"{a['emoji']} {a['name']}" for a in AVATARS]

# ---- Gamification / engine constants ----
XP_PER_LEVEL = 200
XP_READ = 20
XP_CORRECT = 50
PROMOTION_THRESHOLD = 2
NUM_DIAGNOSTIC = 3
GROW_THRESHOLD = 0.70     # accuracy below this (with enough tries) = a "growth area"
GROW_MIN_ATTEMPTS = 3

# Learner-model defaults
DEFAULT_BLUEPRINT = ["Concept Overview", "Core Puzzle A", "Core Puzzle B", "Final Milestone"]
CHALLENGE_NODE = "⚡ [Challenge Quest]"
REMEDIATION_NODE = "🛟 [Remediation Practice Quest]"

OLLAMA_MODEL = "llama3"
GROQ_MODEL = "llama-3.3-70b-versatile"
GROQ_BASE_URL = "https://api.groq.com/openai/v1"


def chapters_for(subject):
    return list(SUBJECTS.get(subject, {}).keys())


def module_key(subject, chapter):
    return f"{subject} :: {chapter}"


def band_for(subject):
    return GOALS.get(subject, {}).get("band", "K-8")


def current_theme():
    """The story theme that styles all generated content (parent-configured)."""
    try:
        theme = st.session_state.story_theme
    except Exception:  # noqa: BLE001
        theme = None
    return (theme or "a fun adventure").strip()


def student_path():
    """Ordered, de-duplicated (track, module) list from parent-approved modules."""
    seen, path = set(), []
    for key in st.session_state.parent_approved_modules:
        if " :: " not in key:
            continue
        track, mod = key.split(" :: ", 1)
        if track in SUBJECTS and mod in SUBJECTS[track] and key not in seen:
            seen.add(key)
            path.append((track, mod))
    return path


# =========================================================================== #
# LLM backend
# =========================================================================== #
def _config(key, default=None):
    try:
        if key in st.secrets:
            return st.secrets[key]
    except Exception:  # noqa: BLE001
        pass
    return os.environ.get(key, default)


def resolve_backend():
    api_key = _config("GROQ_API_KEY")
    forced = (_config("LLM_BACKEND") or "").strip().lower()
    use_groq = forced == "groq" or (forced != "ollama" and bool(api_key))
    if use_groq:
        return {"name": "groq", "model": _config("LLM_MODEL", GROQ_MODEL), "api_key": api_key}
    return {"name": "ollama", "model": _config("LLM_MODEL", OLLAMA_MODEL), "api_key": None}


def _ollama_call(messages, temperature, json_mode):
    if ollama is None:
        raise RuntimeError("The 'ollama' package is not installed.")
    kwargs = {"model": st.session_state.backend["model"], "messages": messages,
              "options": {"temperature": temperature}}
    if json_mode:
        kwargs["format"] = "json"
    return ollama.chat(**kwargs)["message"]["content"]


def _groq_call(messages, temperature, json_mode):
    from openai import OpenAI

    client = OpenAI(api_key=st.session_state.backend["api_key"], base_url=GROQ_BASE_URL)
    kwargs = {"model": st.session_state.backend["model"], "messages": messages,
              "temperature": temperature}
    if json_mode:
        kwargs["response_format"] = {"type": "json_object"}
    return client.chat.completions.create(**kwargs).choices[0].message.content


def _chat(system_prompt, user_prompt, temperature=0.6, json_mode=False, retries=2):
    call = _groq_call if st.session_state.backend["name"] == "groq" else _ollama_call
    messages = [{"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}]
    last_err = None
    for _ in range(retries + 1):
        content = call(messages, temperature, json_mode)
        if not json_mode:
            return content
        try:
            return json.loads(content)
        except (json.JSONDecodeError, TypeError) as exc:
            last_err = exc
    raise ValueError(f"Model did not return valid JSON after retries: {last_err}")


# ---- Kid-friendly, story-driven system voice shared by the generators ----
def _kid_voice(band):
    return (
        f"You are a super-friendly, playful game master teaching {band} kids. "
        "Use simple words, short sentences, a warm encouraging tone, and a fun "
        "adventure theme — frame ideas as magic spells, robot missions, or "
        "spaceship journeys. Add a few emojis. Never use scary jargon or make a "
        "child feel bad. Keep it age-appropriate and joyful."
    )


def _generate_mcq_once(subject, chapter, difficulty):
    desc = SUBJECTS[subject][chapter][difficulty]
    band = band_for(subject)
    theme = current_theme()
    system_prompt = (
        _kid_voice(band) + " You are writing ONE fun multiple-choice puzzle. The "
        "option named by correct_option MUST be truly correct, and the explanation "
        "MUST cheer the child on while matching that exact option (no contradictions). "
        "Respond ONLY with JSON — no markdown fences or extra prose."
    )
    user_prompt = f"""Make one {difficulty}-level puzzle for the "{chapter}" adventure (topic for {band}: {desc}).
Style the WHOLE puzzle around this theme the child loves: {theme}. Keep options short and clear.

Return JSON EXACTLY like:
{{"question": "...", "options": {{"A": "...", "B": "...", "C": "...", "D": "..."}}, "correct_option": "A", "explanation": "a cheerful, simple reason", "hint": "a gentle clue that does NOT reveal the answer"}}
correct_option MUST be one of A, B, C, D, and its option text must be the truly correct answer."""
    data = _chat(system_prompt, user_prompt, temperature=0.7, json_mode=True)
    if not all(k in data for k in ("question", "options", "correct_option", "explanation")):
        raise ValueError(f"Question JSON missing keys: {list(data)}")
    if not isinstance(data["options"], dict) or set(data["options"]) < set("ABCD"):
        raise ValueError("Options must include keys A, B, C, D.")
    if data["correct_option"] not in data["options"]:
        raise ValueError("correct_option does not match an option.")
    return data


def _verify_correct_option(q):
    opts = "\n".join(f"{k}. {v}" for k, v in q["options"].items())
    system_prompt = ("You are a careful exam grader. Decide which single option is "
                     "correct. Respond ONLY with JSON.")
    user_prompt = (f"Question: {q['question']}\nOptions:\n{opts}\n\n"
                   'Return {"correct_option": "X"} where X is the letter (A-D).')
    try:
        v = _chat(system_prompt, user_prompt, temperature=0.0, json_mode=True)
        letter = str(v.get("correct_option", "")).strip().upper()[:1]
        return letter if letter in q["options"] else None
    except Exception:  # noqa: BLE001
        return None


def generate_quiz_question(subject, chapter, difficulty, attempts=2):
    """Generate a self-consistent, kid-friendly puzzle (verified by an LLM grader)."""
    last = None
    for _ in range(attempts):
        q = _generate_mcq_once(subject, chapter, difficulty)
        last = q
        verdict = _verify_correct_option(q)
        if verdict is None or verdict == q["correct_option"]:
            return q
    verdict = _verify_correct_option(last)
    if verdict and verdict in last["options"]:
        last["correct_option"] = verdict
    return last


def generate_study_material(subject, chapter, difficulty):
    desc = SUBJECTS[subject][chapter][difficulty]
    band = band_for(subject)
    theme = current_theme()
    system_prompt = (
        _kid_voice(band) + " Write a tiny, exciting lesson in GitHub-flavored "
        "Markdown: a one-line story hook, 3 simple bullet points (each a friendly "
        "tip), and one quick example framed as a mini adventure. Keep it under ~130 "
        "words. End with a cheerful '🌟 You've got this!' style takeaway. No preamble."
    )
    user_prompt = (f'Teach the "{chapter}" adventure at the {difficulty} level for '
                   f"{band}. Topic: {desc}. Style the whole lesson around this theme the "
                   f"child loves: {theme}.")
    return _chat(system_prompt, user_prompt, temperature=0.6, json_mode=False)


def generate_recovery_recommendation(label, accuracy):
    """One upbeat sentence to help a child grow in a topic (templated fallback)."""
    try:
        system_prompt = ("You are a warm, encouraging learning coach for parents. In "
                         "ONE positive sentence, suggest a fun, simple way to practice a "
                         "topic at home. Stay upbeat — no negative words.")
        user_prompt = (f'The child is still growing their "{label}" skills '
                       f"(around {int(accuracy * 100)}% so far). Suggest one playful practice idea.")
        return _chat(system_prompt, user_prompt, temperature=0.6, json_mode=False).strip()
    except Exception:  # noqa: BLE001
        return (f"Try a quick, playful {label} game together — a few minutes of fun "
                "practice will build confidence fast!")


def generate_tryit_brief(subject, chapter):
    """Short Markdown 'Try-It' brief explaining the module's pedagogy (fallback)."""
    band = band_for(subject)
    try:
        system_prompt = (
            "You are a friendly curriculum designer talking to a parent. In <=110 words "
            "of Markdown, explain the playful teaching strategy for a module and give ONE "
            "60-second at-home activity. Use bold labels **Strategy:** and **Try it (60s):**."
        )
        user_prompt = f'Module: "{chapter}" for {band} learners.'
        return _chat(system_prompt, user_prompt, temperature=0.5, json_mode=False)
    except Exception:  # noqa: BLE001
        return (f"**Strategy:** Short, playful challenges that grow from Explorer → Hero "
                f"with instant encouragement, adapting to your child's pace.\n\n"
                f"**Try it (60s):** Play a quick *{chapter}* guessing game and celebrate "
                "every attempt!")


def parse_custom_parental_goal(text):
    """Map a free-text parent goal to catalog module keys using the LLM.

    Returns a list of module keys (possibly empty if nothing matched / errored).
    """
    name_to_key, catalog_lines = {}, []
    for track, mods in SUBJECTS.items():
        for mod in mods:
            name_to_key[mod] = module_key(track, mod)
            catalog_lines.append(f"- {mod} [{band_for(track)}]: {SUBJECTS[track][mod]['Novice']}")
    catalog = "\n".join(catalog_lines)
    system_prompt = (
        "You are a K-12 learning planner. From the FIXED module catalog, choose the "
        "2-4 modules that best match the parent's goal or the child's interest. Use "
        "ONLY exact module names from the catalog. Respond ONLY with JSON."
    )
    user_prompt = (f'Parent goal / interest: "{text}"\n\nModule catalog:\n{catalog}\n\n'
                   'Return {"modules": ["Exact Module Name", ...]} with 2-4 names from the catalog.')
    try:
        data = _chat(system_prompt, user_prompt, temperature=0.2, json_mode=True)
        picked = [m for m in data.get("modules", []) if m in name_to_key]
        return [name_to_key[m] for m in dict.fromkeys(picked)]  # dedup, keep order
    except Exception:  # noqa: BLE001
        return []


def list_local_models():
    data = ollama.list()
    models = getattr(data, "models", None)
    if models is None and isinstance(data, dict):
        models = data.get("models", [])
    names = []
    for m in models or []:
        name = getattr(m, "model", None)
        if name is None and isinstance(m, dict):
            name = m.get("model") or m.get("name")
        if name:
            names.append(name)
    return names


def model_is_available(model, names):
    base = model.split(":")[0]
    return any(n == model or n.split(":")[0] == base for n in names)


def render_llm_error(exc):
    backend = st.session_state.backend
    if backend["name"] == "groq":
        st.error("**Couldn't reach the Groq API.** Check `GROQ_API_KEY` is set and the "
                 f"model `{backend['model']}` is valid / has quota.\n\nDetails: `{exc}`")
    else:
        st.error("**Couldn't reach the local model.**\n\n1. `ollama serve`\n"
                 f"2. `ollama pull {backend['model']}`\n\nDetails: `{exc}`")


# =========================================================================== #
# Session state
# =========================================================================== #
def init_state():
    defaults = {
        "backend": resolve_backend(),
        "role": "Student",
        # Source of truth for the student's unlocked path (set by presets / custom AI):
        "parent_approved_modules": [module_key(LOGIC, m) for m in chapters_for(LOGIC)],
        "story_theme": GOALS[LOGIC]["theme"],
        "skill_gaps": {},            # module_key -> {"correct": int, "total": int}
        "student_stats": {"xp": 0, "level": 1, "streak": 0, "avatar": AVATAR_LABELS[0]},
        "badges": [],
        "consecutive_correct": 0,
        "completed_modules": [],
        # --- Learner model (visible intelligence layer) ---
        "mastery_score": 50,             # 0-100, starts neutral
        "attempts_on_current_item": 0,   # wrong tries on the active puzzle
        "hint_used": False,
        "original_path": list(DEFAULT_BLUEPRINT),
        "live_path": list(DEFAULT_BLUEPRINT),
        "path_index": 0,
        "mastery_reason": "Welcome! Answer puzzles to evolve your path. 🚀",
        "phase": "PATH",             # PATH | DIAGNOSTIC | STUDY | QUIZ
        "current_subject": None,
        "current_chapter": None,
        "current_difficulty": "Novice",
        "baseline_skill": None,
        "module_complete": False,
        "just_leveled": False,
        "diag_index": 0,
        "diag_correct": 0,
        "diag_question": None,
        "study_content": None,
        "study_read": False,
        "quiz_question": None,
        "quiz_result": None,
        "tryit_cache": {},
    }
    for key, value in defaults.items():
        st.session_state.setdefault(key, value)


def start_module(subject, chapter):
    s = st.session_state
    s.current_subject = subject
    s.current_chapter = chapter
    s.current_difficulty = "Novice"
    s.baseline_skill = None
    s.module_complete = False
    s.diag_index = 0
    s.diag_correct = 0
    s.diag_question = None
    s.study_content = None
    s.study_read = False
    s.quiz_question = None
    s.quiz_result = None
    # Fresh learning blueprint for this module (mastery_score persists as the
    # cumulative learner model and keeps shaping the path).
    s.original_path = list(DEFAULT_BLUEPRINT)
    s.path_index = 0
    s.attempts_on_current_item = 0
    s.hint_used = False
    update_live_path()
    s.phase = "DIAGNOSTIC"


def back_to_path():
    s = st.session_state
    s.phase = "PATH"
    s.current_subject = None
    s.current_chapter = None


# =========================================================================== #
# Gamification + growth tracking
# =========================================================================== #
def add_xp(amount):
    stats = st.session_state.student_stats
    stats["xp"] += amount
    new_level = 1 + stats["xp"] // XP_PER_LEVEL
    if new_level > stats["level"]:
        stats["level"] = new_level
        st.session_state.just_leveled = True


def completed_module_names():
    return {key.split(" :: ")[-1] for key in st.session_state.completed_modules}


def completed_in_track(track):
    return any(key.startswith(track + " :: ") for key in st.session_state.completed_modules)


def check_badges():
    s = st.session_state
    stats = s.student_stats
    done = completed_module_names()
    rules = [
        ("🎯 First Quest", stats["xp"] > 0),
        ("🔥 Streak Star", stats["streak"] >= 3),
        ("⚡ Puzzle Champ", stats["streak"] >= 5),
        ("🌟 Rising Star", stats["level"] >= 2),
        ("🧙 Logic Wizard", completed_in_track(LOGIC)),
        ("🔁 Loop Master", "Loop Patterns" in done),
        ("🤖 Robot Boss", "Robot Commands" in done),
        ("🚀 Game Builder", "Text-Adventure Game Building" in done),
        ("🧠 Brainiac", s.baseline_skill == "Expert"),
    ]
    newly = []
    for title, cond in rules:
        if cond and title not in s.badges:
            s.badges.append(title)
            newly.append(title)
    return newly


def _record_accuracy(correct):
    key = module_key(st.session_state.current_subject, st.session_state.current_chapter)
    bucket = st.session_state.skill_gaps.setdefault(key, {"correct": 0, "total": 0})
    bucket["total"] += 1
    if correct:
        bucket["correct"] += 1


def _advance_or_complete():
    s = st.session_state
    idx = TIERS.index(s.current_difficulty)
    if idx < len(TIERS) - 1:
        s.current_difficulty = TIERS[idx + 1]
        return f"🎉 Level up! You're now a **{TIER_LABELS[s.current_difficulty]}**!"
    key = module_key(s.current_subject, s.current_chapter)
    if key not in s.completed_modules:
        s.completed_modules.append(key)
    s.module_complete = True
    return "🏆 Quest complete — you mastered this adventure!"


def _demote():
    # Gentle, safe self-adjust: never drops below the easiest tier, always kind.
    s = st.session_state
    idx = TIERS.index(s.current_difficulty)
    if idx > 0:
        s.current_difficulty = TIERS[idx - 1]
        return (f"💛 No worries! Let's warm up at **{TIER_LABELS[s.current_difficulty]}** "
                "and try again.")
    return "💪 Great try! We'll keep practicing here — you're getting stronger!"


def record_correct():
    s = st.session_state
    _record_accuracy(True)
    add_xp(XP_CORRECT)
    s.student_stats["streak"] += 1
    s.consecutive_correct += 1
    if s.consecutive_correct >= PROMOTION_THRESHOLD:
        s.consecutive_correct = 0
        return _advance_or_complete()
    remaining = PROMOTION_THRESHOLD - s.consecutive_correct
    return f"✅ Yes! +{XP_CORRECT} XP · {remaining} more win to level up!"


def record_wrong():
    s = st.session_state
    _record_accuracy(False)
    s.student_stats["streak"] = 0
    s.consecutive_correct = 0
    return _demote()


def growth_areas():
    """List of (module_key, accuracy) below threshold with enough attempts."""
    out = []
    for key, v in st.session_state.skill_gaps.items():
        if v["total"] >= GROW_MIN_ATTEMPTS:
            acc = v["correct"] / v["total"]
            if acc < GROW_THRESHOLD:
                out.append((key, acc))
    return out


# ---- Learner model: path evolution + mastery scoring ----
def update_live_path():
    """Recompute live_path from original_path based on mastery (idempotent).

    >80 → Acceleration (insert a Challenge Quest after the active node);
    <50 → Remediation (inject a Practice Quest before the next core node);
    50-80 → maintain the baseline blueprint unchanged.
    """
    s = st.session_state
    path = list(s.original_path)
    if not path:
        s.live_path = []
        return
    idx = min(s.path_index, len(path) - 1)
    if s.mastery_score > 80:
        path.insert(idx + 1, CHALLENGE_NODE)
        # Strong mastery also skips the next basic module entirely (Skip mode).
        if s.mastery_score >= 90 and idx + 2 < len(path):
            path.pop(idx + 2)
    elif s.mastery_score < 50:
        path.insert(min(idx + 1, len(path)), REMEDIATION_NODE)
    s.live_path = path


def apply_mastery(delta, why):
    """Adjust mastery (clamped 0-100), redraw the path, and log the reasoning."""
    s = st.session_state
    s.mastery_score = max(0, min(100, s.mastery_score + delta))
    update_live_path()
    sign = f"+{delta}" if delta > 0 else (str(delta) if delta < 0 else "±0")
    if s.mastery_score > 80:
        branch = "Acceleration unlocked — a Challenge Quest was inserted! ⚡"
    elif s.mastery_score < 50:
        branch = "Remediation branch unlocked to bridge the gap. 🛟"
    else:
        branch = "Course maintained — steady progress."
    s.mastery_reason = f"System Alert: Mastery {sign} ({why}). {branch}"


def advance_path_node():
    s = st.session_state
    s.path_index = min(s.path_index + 1, max(0, len(s.original_path) - 1))
    update_live_path()


def _breadcrumb(nodes, active_name):
    chips = []
    for n in nodes:
        if n.startswith(("⚡", "🛟")):
            cls = "node node-new"
        elif n == active_name:
            cls = "node node-active"
        else:
            cls = "node"
        chips.append(f'<span class="{cls}">{n}</span>')
    return '<div class="path-row">' + " ➔ ".join(chips) + "</div>"


def render_path_map():
    """The Path Evolution Map: original blueprint vs the live, mutating path."""
    s = st.session_state
    if not s.original_path:
        return
    active_name = s.original_path[min(s.path_index, len(s.original_path) - 1)]
    st.markdown("##### 🗺️ Path Evolution Map")
    col1, col2 = st.columns(2)
    with col1:
        st.markdown("**Originally Planned Path:**")
        st.markdown(_breadcrumb(s.original_path, active_name), unsafe_allow_html=True)
    with col2:
        st.markdown("**Updated Live Path:**")
        st.markdown(_breadcrumb(s.live_path, active_name), unsafe_allow_html=True)


def render_mastery_alert():
    s = st.session_state
    reason = s.mastery_reason
    if not reason:
        return
    if s.mastery_score < 50:
        st.warning(reason)
    elif s.mastery_score > 80:
        st.success(reason)
    else:
        st.info(reason)


def build_digest_payload():
    s = st.session_state
    stats = s.student_stats
    return {
        "type": "weekly_family_update",
        "to": "parent@example.com",
        "child": {"avatar": stats["avatar"], "level": stats["level"],
                  "xp": stats["xp"], "win_streak": stats["streak"],
                  "mastery_score": s.mastery_score},
        "story_theme": st.session_state.story_theme,
        "active_modules": [c for _, c in student_path()],
        "quests_completed": len(s.completed_modules),
        "growth_areas": [
            {"topic": k.split(" :: ")[-1], "progress": round(v["correct"] / v["total"], 2)}
            for k, v in s.skill_gaps.items()
            if v["total"] >= GROW_MIN_ATTEMPTS and v["correct"] / v["total"] < GROW_THRESHOLD
        ],
        "next_send": "Mon 09:00 (simulated)",
    }


# =========================================================================== #
# Sidebar — Access Portal + kid profile / controls
# =========================================================================== #
def render_sidebar():
    s = st.session_state
    stats = s.student_stats
    # Key-bound avatar: reflect the latest pick into stats BEFORE the profile card
    # renders, so a new avatar shows on the same single click.
    st.session_state.setdefault("avatar_choice", stats["avatar"])
    stats["avatar"] = st.session_state.avatar_choice
    emoji, _, name = stats["avatar"].partition(" ")

    with st.sidebar:
        st.markdown('<div class="hud-title">🛂 Access Portal</div>', unsafe_allow_html=True)
        # Key-bound: changing it updates st.session_state.role and triggers
        # Streamlit's built-in rerun on a single click. (No on_change=st.rerun —
        # that's a no-op inside a callback and pops a warning.)
        st.radio("Access Portal", ["Student", "Parent"], key="role",
                 horizontal=True, label_visibility="collapsed")

        xp_in_level = stats["xp"] % XP_PER_LEVEL
        pct = int(100 * xp_in_level / XP_PER_LEVEL)
        flames = "🔥" * min(stats["streak"], 6) or "—"
        st.markdown(
            f"""
            <div class="hud-card">
              <div class="profile-avatar">{emoji}</div>
              <div class="profile-name">{name or 'Player'}</div>
              <div class="hud-title">⚡ Level {stats['level']}</div>
              <div class="xp-bar"><div class="xp-fill" style="width:{pct}%"></div></div>
              <div class="xp-text">{xp_in_level} / {XP_PER_LEVEL} XP · {stats['xp']} total</div>
              <div class="mastery-meter">🧠 Mastery {s.mastery_score}/100</div>
              <div class="streak-meter">Win streak: {flames} ({stats['streak']})</div>
              <div class="hud-row"><span class="k">Quests done</span><span class="v">{len(s.completed_modules)}</span></div>
            </div>
            """,
            unsafe_allow_html=True,
        )

        badge_html = ("".join(f'<span class="badge">{b}</span>' for b in s.badges)
                      if s.badges else '<span class="badge-empty">Earn your first badge!</span>')
        st.markdown(f'<div class="hud-card"><div class="hud-title">🏅 Badge Case</div>'
                    f"{badge_html}</div>", unsafe_allow_html=True)

        if s.role == "Student":
            st.selectbox("🎭 Choose your hero", AVATAR_LABELS, key="avatar_choice")
            if s.current_subject and st.button("🔁 Back to Quest Map", use_container_width=True):
                back_to_path()
                st.rerun()


def celebrate_levelups():
    if st.session_state.just_leveled:
        st.balloons()
        st.success(f"⚡ LEVEL UP! You reached **Level {st.session_state.student_stats['level']}**! 🎉")
        st.session_state.just_leveled = False
    for title in check_badges():
        st.toast(f"🏅 New badge: {title}!")


def ensure_backend_ready():
    backend = st.session_state.backend
    if backend["name"] == "groq":
        if not backend["api_key"]:
            st.error("**No `GROQ_API_KEY` configured.** Add it to Streamlit secrets or env.")
            return False
        return True
    try:
        names = list_local_models()
    except Exception as exc:  # noqa: BLE001
        render_llm_error(exc)
        if st.button("Retry connection"):
            st.rerun()
        return False
    if not model_is_available(backend["model"], names):
        st.warning(f"Model **{backend['model']}** isn't pulled. Run "
                   f"`ollama pull {backend['model']}` (have: {', '.join(names) or 'none'}).")
        if st.button("Retry"):
            st.rerun()
        return False
    return True


# =========================================================================== #
# PARENT PORTAL
# =========================================================================== #
def render_parent_portal():
    s = st.session_state
    stats = s.student_stats
    st.title("🛰️ FAMILY DASHBOARD")
    st.caption("Choose adventures · track foundational growth · peek at the strategy")

    # --- 1. Hybrid goal configuration ---
    st.markdown("### 🎯 Configure the Learning Path")
    preset_tab, custom_tab = st.tabs(["⚡ Quick-Start Presets", "✨ Custom AI Goal"])

    with preset_tab:
        st.caption("Pick a curated, age-appropriate outcome. One click sets the path + story theme.")
        preset = st.selectbox(
            "Curated outcome", list(GOALS.keys()),
            format_func=lambda g: f"{GOALS[g]['icon']} {g}  ·  {GOALS[g]['band']}",
        )
        st.caption(GOALS[preset]["desc"] + f"  ·  theme: _{GOALS[preset]['theme']}_")
        if st.button("🚀 Apply Preset Track", type="primary"):
            s.parent_approved_modules = [module_key(t, c) for t, c in GOALS[preset]["modules"]]
            s.story_theme = GOALS[preset]["theme"]
            st.success(f"Preset applied: **{preset}** — theme “{s.story_theme}”.")
            st.rerun()

    with custom_tab:
        custom = st.text_area(
            "Or, customize a specific milestone or personal interest for your child:",
            placeholder="e.g. My daughter loves dinosaurs and I want her to learn step-by-step logic.",
        )
        if st.button("✨ Generate Custom Track", type="primary"):
            if not custom.strip():
                st.warning("Type an interest or goal first!")
            else:
                with st.spinner("Designing a custom track with AI…"):
                    keys = parse_custom_parental_goal(custom)
                if not keys:
                    keys = [module_key(LOGIC, m) for m in chapters_for(LOGIC)]
                    st.warning("Couldn't match specific modules — starting with Logic basics. "
                               "Try rephrasing the goal.")
                s.parent_approved_modules = keys
                s.story_theme = custom.strip()           # capture the parent's own wording
                st.success(f"Custom track ready: **{len(keys)} module(s)** · "
                           f"theme “{s.story_theme[:50]}”.")
                st.rerun()

    # Current plan summary
    path = student_path()
    with st.container(border=True):
        st.markdown(f"**🎒 Current plan**  ·  story theme: _{s.story_theme or '—'}_")
        if path:
            st.markdown("**Unlocked modules:** " + ", ".join(c for _, c in path))
        else:
            st.warning("No modules unlocked yet — apply a preset or generate a custom track.")

    # --- 2. Foundational growth tracker ---
    st.markdown("### 📊 Foundational Growth")
    st.markdown(
        f"""
        <div class="parent-card"><div class="tile-row">
          <div class="stat-tile"><div class="num">{s.mastery_score}</div><div class="lbl">Mastery</div></div>
          <div class="stat-tile"><div class="num">{stats['level']}</div><div class="lbl">Level</div></div>
          <div class="stat-tile"><div class="num">{stats['xp']}</div><div class="lbl">Total XP</div></div>
          <div class="stat-tile"><div class="num">{stats['streak']}</div><div class="lbl">Win Streak</div></div>
          <div class="stat-tile"><div class="num">{len(s.completed_modules)}</div><div class="lbl">Quests</div></div>
          <div class="stat-tile"><div class="num">{len(s.badges)}</div><div class="lbl">Badges</div></div>
        </div></div>
        """,
        unsafe_allow_html=True,
    )
    # Mirror the live Path Evolution Map + latest reasoning for the parent.
    render_mastery_alert()
    render_path_map()

    # --- 3. Growth spotlights (encouraging skill-gap framing) ---
    st.markdown("### 🌱 Growth Spotlights")
    areas = growth_areas()
    if not areas:
        st.info("No growth spotlights yet — everything's on track! Areas appear here (kindly) "
                f"when a topic is still below {int(GROW_THRESHOLD * 100)}% so you can cheer it on.")
    for key, acc in areas:
        topic = key.split(" :: ")[-1]
        tip = generate_recovery_recommendation(topic, acc)
        st.markdown(
            f"""
            <div class="grow-card">
              <div class="topic">🌱 Still Growing — {topic}</div>
              <div>Progress so far: <b>{int(acc * 100)}%</b> — a great chance to practice together!</div>
            </div>
            <div class="rec-card"><div class="tag">🤖 Friendly Coach Tip</div>
              <p style="margin-top:8px;">{tip}</p></div>
            """,
            unsafe_allow_html=True,
        )

    # --- 4. 60-second module peeks ---
    st.markdown("### 🧪 60-Second Module Peeks")
    st.caption("See exactly how each module is taught — and a quick activity to try at home.")
    path = student_path()
    if path:
        labels = [f"{ch}  ·  {GOALS[subj]['band']}" for subj, ch in path]
        pick = st.selectbox("Choose a module to preview", labels)
        subj, chap = path[labels.index(pick)]
        if st.button("▶ Show 60-second peek", type="primary"):
            mkey = module_key(subj, chap)
            if mkey not in s.tryit_cache:
                with st.spinner("Writing a friendly teaching brief…"):
                    s.tryit_cache[mkey] = generate_tryit_brief(subj, chap)
            st.rerun()
        for subj2, chap2 in path:
            mkey = module_key(subj2, chap2)
            if mkey in s.tryit_cache:
                with st.container(border=True):
                    st.markdown(f"**🧪 {chap2}**")
                    st.markdown(s.tryit_cache[mkey])
    else:
        st.caption("Select an adventure above to preview its modules.")

    # --- 5. Weekly family update (simulated sync) ---
    st.markdown("### 📡 Progress Sync Alerts")
    st.markdown('<div class="digest-card"><div class="hdr">📬 WEEKLY FAMILY UPDATE · '
                'auto-send simulation</div></div>', unsafe_allow_html=True)
    if st.button("🔄 Generate weekly update payload"):
        payload = build_digest_payload()
        print("\n[PROGRESS SYNC] " + json.dumps(payload))
        st.toast("Weekly family update queued (simulated).")
    st.code(json.dumps(build_digest_payload(), indent=2), language="json")


# =========================================================================== #
# STUDENT ARENA
# =========================================================================== #
def phase_path():
    s = st.session_state
    emoji = s.student_stats["avatar"].partition(" ")[0]
    st.title(f"{emoji} QUEST MAP")
    st.caption("Pick a quest and start your adventure! 🚀")
    path = student_path()
    if not path:
        st.info("🔒 No quests yet — ask a grown-up to choose your learning adventures in the "
                "Parent portal (sidebar toggle).")
        return
    cols = st.columns(2)
    for i, (subject, chapter) in enumerate(path):
        key = module_key(subject, chapter)
        done = key in s.completed_modules
        status = "✅ Done — replay anytime!" if done else "✨ Ready to play"
        with cols[i % 2]:
            st.markdown(
                f'<div class="mission-card"><div class="title">{GOALS[subject]["icon"]} {chapter}</div>'
                f'<div class="blurb">{GOALS[subject]["band"]} · {status}</div></div>',
                unsafe_allow_html=True,
            )
            label = "↺ Play Again" if done else "▶ Start Quest"
            if st.button(label, key=f"mod_{i}", use_container_width=True):
                start_module(subject, chapter)
                st.rerun()
            st.write("")


def _finalize_diagnostic():
    s = st.session_state
    correct = s.diag_correct
    baseline = "Novice" if correct <= 1 else "Intermediate" if correct == 2 else "Expert"
    s.baseline_skill = baseline
    s.current_difficulty = baseline
    s.phase = "STUDY"
    s.study_content = None
    s.study_read = False
    check_badges()


def phase_diagnostic():
    s = st.session_state
    st.title("🧪 WARM-UP CHALLENGE")
    st.caption(f"{s.current_chapter} · finding your starting level — just do your best! 💪")
    if s.diag_index >= NUM_DIAGNOSTIC:
        _finalize_diagnostic()
        st.rerun()
        return
    probe_tier = TIERS[s.diag_index]
    if s.diag_question is None:
        with st.spinner(f"Loading warm-up {s.diag_index + 1}/{NUM_DIAGNOSTIC}…"):
            try:
                s.diag_question = generate_quiz_question(s.current_subject, s.current_chapter, probe_tier)
            except Exception as exc:  # noqa: BLE001
                render_llm_error(exc)
                if st.button("Try again"):
                    st.rerun()
                return
    q = s.diag_question
    st.progress(s.diag_index / NUM_DIAGNOSTIC, text=f"Warm-up {s.diag_index + 1} of {NUM_DIAGNOSTIC}")
    with st.container(border=True):
        st.markdown(f"**[{TIER_LABELS[probe_tier]}]** {q['question']}")
        choice = st.radio("Your answer:", list("ABCD"),
                          format_func=lambda k: f"{k}.  {q['options'][k]}",
                          index=None, key=f"diag_{s.diag_index}")
        if st.button("Submit ▶", type="primary"):
            if choice is None:
                st.warning("Pick an answer to keep going!")
            else:
                if choice == q["correct_option"]:
                    s.diag_correct += 1
                s.diag_index += 1
                s.diag_question = None
                st.rerun()


def phase_study():
    s = st.session_state
    st.title("📖 STORY TIME")
    st.caption(f"{s.current_chapter} · {TIER_LABELS[s.current_difficulty]}")
    if s.baseline_skill:
        st.markdown(f"Your warm-up placed you at **{TIER_LABELS[s.baseline_skill]}**! 🌟")
    render_path_map()
    if s.study_content is None:
        with st.spinner("Writing your adventure briefing…"):
            try:
                s.study_content = generate_study_material(
                    s.current_subject, s.current_chapter, s.current_difficulty)
            except Exception as exc:  # noqa: BLE001
                render_llm_error(exc)
                if st.button("Try again"):
                    st.rerun()
                return
    with st.container(border=True):
        st.markdown(s.study_content)
    col1, col2 = st.columns(2)
    with col1:
        if not s.study_read:
            if st.button(f"📗 I Read It! (+{XP_READ} XP)", type="primary", use_container_width=True):
                add_xp(XP_READ)
                s.study_read = True
                st.rerun()
        else:
            st.success(f"✓ +{XP_READ} XP earned")
    with col2:
        if s.study_read and st.button("⚔️ Start the Puzzle →", type="primary",
                                      use_container_width=True):
            s.phase = "QUIZ"
            s.quiz_question = None
            s.quiz_result = None
            st.rerun()
    celebrate_levelups()


def phase_quiz():
    s = st.session_state
    st.title("⚔️ PUZZLE ARENA")
    st.caption(f"{s.current_chapter} · {TIER_LABELS[s.current_difficulty]}")
    render_mastery_alert()
    render_path_map()

    if s.quiz_question is None:
        s.attempts_on_current_item = 0      # fresh item → reset retry/hint trackers
        s.hint_used = False
        with st.spinner("Summoning your puzzle…"):
            try:
                s.quiz_question = generate_quiz_question(
                    s.current_subject, s.current_chapter, s.current_difficulty)
            except Exception as exc:  # noqa: BLE001
                render_llm_error(exc)
                if st.button("Try again"):
                    st.rerun()
                return
    q = s.quiz_question

    # ---- Unresolved: allow retries, hints, or skipping ----
    if s.quiz_result is None:
        with st.container(border=True):
            st.markdown(f"### {q['question']}")
            if s.hint_used:
                st.info(f"💡 Hint: {q.get('hint', 'Take it one step at a time — you can do it!')}")
            if s.attempts_on_current_item:
                st.caption(f"Tries so far: {s.attempts_on_current_item} — keep going! 💪")
            choice = st.radio("Pick your answer:", list("ABCD"),
                              format_func=lambda k: f"{k}.  {q['options'][k]}",
                              index=None, key=f"quiz_choice_{s.attempts_on_current_item}")
            c1, c2, c3 = st.columns(3)
            submit = c1.button("🎯 Lock It In!", type="primary", use_container_width=True)
            hint = c2.button("💡 Hint", use_container_width=True)
            skip = c3.button("⏭️ Skip", use_container_width=True)

        if hint:
            s.hint_used = True
            st.rerun()

        if skip:
            apply_mastery(-3, "skipped the question")
            transition = record_wrong()
            advance_path_node()
            s.quiz_result = {
                "correct": False, "skipped": True, "your_answer": "(skipped)",
                "correct_answer": f"{q['correct_option']}. {q['options'][q['correct_option']]}",
                "explanation": q["explanation"], "transition": transition,
            }
            st.rerun()

        if submit:
            if choice is None:
                st.warning("Pick an answer first!")
            elif choice == q["correct_option"]:
                if s.hint_used:
                    apply_mastery(5, "correct after a hint")
                elif s.attempts_on_current_item == 0:
                    apply_mastery(10, "correct on the first try")
                else:
                    apply_mastery(5, "correct after retrying")
                transition = record_correct()
                advance_path_node()
                s.quiz_result = {
                    "correct": True, "skipped": False,
                    "your_answer": f"{choice}. {q['options'][choice]}",
                    "correct_answer": f"{q['correct_option']}. {q['options'][q['correct_option']]}",
                    "explanation": q["explanation"], "transition": transition,
                }
                st.rerun()
            else:
                s.attempts_on_current_item += 1
                tries = s.attempts_on_current_item
                if tries >= 3:
                    apply_mastery(-15, "3+ retries (exponential downgrade)")
                elif tries == 2:
                    apply_mastery(-5, "two wrong tries")
                else:
                    s.mastery_reason = "🤔 First miss — no penalty. Give it another go!"
                if tries >= 2:
                    s.hint_used = True   # auto-reveal the hint to help them through
                st.rerun()
        return

    # ---- Resolved: feedback + next step ----
    r = s.quiz_result
    with st.container(border=True):
        if r["correct"]:
            st.success("✅ WOOHOO — that's right! 🎉")
            st.balloons()
        else:
            st.warning("⏭️ Skipped — here's the answer:" if r.get("skipped")
                       else "💛 Good try! Here's the answer:")
            st.markdown(f"**You picked:** {r['your_answer']}")
            st.markdown(f"**Answer:** {r['correct_answer']}")
        st.info(f"**Why:** {r['explanation']}")
        st.markdown(f"*{r['transition']}*")
    celebrate_levelups()
    if s.module_complete:
        st.success("🎓 Quest complete — amazing work, hero!")
        if st.button("🗺️ Back to Quest Map", type="primary"):
            back_to_path()
            st.rerun()
    elif st.button("Next puzzle →", type="primary"):
        s.study_content = None
        s.study_read = False
        s.quiz_question = None
        s.quiz_result = None
        s.attempts_on_current_item = 0
        s.hint_used = False
        s.phase = "STUDY"
        st.rerun()


STUDENT_PHASES = {
    "PATH": phase_path,
    "DIAGNOSTIC": phase_diagnostic,
    "STUDY": phase_study,
    "QUIZ": phase_quiz,
}


def render_student_arena():
    s = st.session_state
    if s.phase == "PATH" or not s.current_subject:
        phase_path()
        return
    path_keys = {module_key(sub, ch) for sub, ch in student_path()}
    if module_key(s.current_subject, s.current_chapter) not in path_keys:
        st.toast("That quest isn't on your map right now.")
        back_to_path()
        phase_path()
        return
    if not ensure_backend_ready():
        return
    STUDENT_PHASES.get(s.phase, phase_path)()


# =========================================================================== #
# Main
# =========================================================================== #
st.set_page_config(page_title="Adaptive Tutor · Kids", page_icon="🚀", layout="centered")
init_state()
st.markdown(STUDENT_CSS if st.session_state.role == "Student" else PARENT_CSS,
            unsafe_allow_html=True)
render_sidebar()

if st.session_state.role == "Parent":
    render_parent_portal()
else:
    render_student_arena()
