"""Adaptive Tutor — a gamified, AI-driven adaptive learning arcade.

A state-driven, 4-phase learning experience with a cyberpunk dark-mode UI:

    SUBJECT_SELECTION → DIAGNOSTIC → STUDY ⇄ QUIZ

Content (study notes, diagnostic + quiz questions) is generated by a Llama 3
model. Backend is auto-detected:
    - Local dev → Ollama (`ollama serve` + `ollama pull llama3`), the default.
    - Cloud     → Groq's free Llama 3 API when GROQ_API_KEY is set (so this same
                  file deploys to Streamlit Community Cloud unchanged).

Run locally:
    streamlit run app.py
"""

import json
import os

import streamlit as st

try:  # Optional locally; only needed for the Ollama backend.
    import ollama
except ImportError:  # pragma: no cover
    ollama = None

# =========================================================================== #
# Theme — cyberpunk / arcade dark mode injected over Streamlit's defaults.
# =========================================================================== #
OBSIDIAN = "#0B0C10"
SILVER = "#C5C6C7"
CYAN = "#00E5FF"
GUNMETAL = "#1F2833"
PINK = "#FF007F"

CUSTOM_CSS = """
<style>
/* ---- Global palette ---- */
.stApp {
    background: radial-gradient(circle at 20% 0%, #12141c 0%, #0B0C10 60%);
    color: #C5C6C7;
}
.stApp, .stMarkdown, p, span, label, li { color: #C5C6C7 !important; }
h1, h2, h3, h4 { color: #00E5FF !important; letter-spacing: 0.5px; }
h1 { text-shadow: 0 0 12px rgba(0,229,255,0.55); }
a { color: #FF007F !important; }

/* ---- Sidebar HUD ---- */
[data-testid="stSidebar"] {
    background: linear-gradient(180deg, #0e1117 0%, #1F2833 100%);
    border-right: 1px solid rgba(0,229,255,0.25);
}
.hud-card {
    background: #1F2833;
    border: 1px solid rgba(0,229,255,0.35);
    border-radius: 14px;
    padding: 16px;
    margin-bottom: 16px;
    box-shadow: 0 0 18px rgba(0,229,255,0.12);
}
.hud-title {
    color: #00E5FF; font-weight: 800; font-size: 1.05rem;
    text-transform: uppercase; letter-spacing: 1.5px;
    text-shadow: 0 0 8px rgba(0,229,255,0.6); margin-bottom: 10px;
}
.hud-row { display:flex; justify-content:space-between; font-size:0.9rem; margin:4px 0; }
.hud-row .k { color:#7f8c8d; }
.hud-row .v { color:#C5C6C7; font-weight:700; }
.xp-bar {
    width:100%; height:16px; background:#0B0C10; border-radius:10px;
    border:1px solid rgba(0,229,255,0.4); overflow:hidden; margin:6px 0;
}
.xp-fill {
    height:100%; background:linear-gradient(90deg,#00E5FF,#FF007F);
    box-shadow:0 0 12px rgba(0,229,255,0.8); transition:width 0.5s ease;
}
.xp-text { font-size:0.78rem; color:#7f8c8d; text-align:right; }
.badge {
    display:inline-block; margin:4px 4px 0 0; padding:5px 10px;
    background:#0B0C10; border:1px solid #FF007F; border-radius:20px;
    font-size:0.72rem; color:#FF007F; font-weight:700;
    box-shadow:0 0 8px rgba(255,0,127,0.45);
}
.badge-empty { font-size:0.78rem; color:#566573; font-style:italic; }
.streak-flame { font-size:1.4rem; text-shadow:0 0 10px rgba(255,0,127,0.8); }

/* ---- Game cards (bordered containers) ---- */
[data-testid="stVerticalBlockBorderWrapper"] {
    background: #1F2833;
    border: 1px solid rgba(0,229,255,0.30) !important;
    border-radius: 16px !important;
    box-shadow: 0 0 22px rgba(0,229,255,0.10);
    padding: 6px 4px;
}
code, pre { background:#0B0C10 !important; border:1px solid rgba(0,229,255,0.25); }

/* ---- Subject grid cards ---- */
.subject-card {
    background:#1F2833; border:1px solid rgba(0,229,255,0.30);
    border-radius:16px; padding:18px; min-height:120px;
    box-shadow:0 0 18px rgba(0,229,255,0.10);
}
.subject-card .title { color:#00E5FF; font-weight:800; font-size:1.1rem; }
.subject-card .blurb { color:#9aa0a6; font-size:0.85rem; margin-top:6px; }

/* ---- Neon buttons with glow animation ---- */
.stButton > button {
    background: #0B0C10;
    color: #FF007F !important;
    border: 2px solid #FF007F;
    border-radius: 12px;
    font-weight: 800;
    letter-spacing: 0.6px;
    padding: 0.5rem 1rem;
    transition: all 0.2s ease-in-out;
    box-shadow: 0 0 10px rgba(255,0,127,0.4);
}
.stButton > button:hover {
    color: #0B0C10 !important;
    background: #FF007F;
    transform: translateY(-2px) scale(1.02);
    box-shadow: 0 0 22px rgba(255,0,127,0.95), 0 0 40px rgba(255,0,127,0.5);
}
.stButton > button[kind="primary"] {
    border-color:#00E5FF; color:#00E5FF !important;
    box-shadow:0 0 12px rgba(0,229,255,0.6);
    animation: pulse 1.8s infinite;
}
.stButton > button[kind="primary"]:hover {
    background:#00E5FF; color:#0B0C10 !important;
}
@keyframes pulse {
    0%   { box-shadow:0 0 8px rgba(0,229,255,0.5); }
    50%  { box-shadow:0 0 22px rgba(0,229,255,0.95); }
    100% { box-shadow:0 0 8px rgba(0,229,255,0.5); }
}

/* ---- Radio options ---- */
[data-testid="stRadio"] label { color:#C5C6C7 !important; }
</style>
"""

# =========================================================================== #
# Curriculum — subject → chapter (ordered) → tier → guidance for the model.
# =========================================================================== #
TIERS = ["Novice", "Intermediate", "Expert"]

SUBJECTS = {
    "Basic Python Programming": {
        "Chapter 1: Variables & Data Types": {
            "Novice": "Variables, assignment, and core types (int, float, str, bool).",
            "Intermediate": "Type conversion, f-strings, predicting expression types/values.",
            "Expert": "Mutability, reference semantics, truthiness, coercion edge cases.",
        },
        "Chapter 2: Conditionals & Loops": {
            "Novice": "if/else, comparisons, simple for/while loops.",
            "Intermediate": "elif chains, nested loops, break/continue, tracing output.",
            "Expert": "loop/else, off-by-one, short-circuiting, comprehensions.",
        },
        "Chapter 3: Functions": {
            "Novice": "Defining/calling functions, parameters, return values.",
            "Intermediate": "Default args, keyword vs positional, local vs global scope.",
            "Expert": "*args/**kwargs, mutable-default pitfalls, closures, higher-order fns.",
        },
    },
    "Data Structures & Algorithms": {
        "Chapter 1: Arrays & Linked Lists": {
            "Novice": "Arrays/lists, indexing, append/insert/remove.",
            "Intermediate": "Complexity of list ops, singly vs doubly linked lists.",
            "Expert": "Amortised analysis of dynamic arrays, pointer edge cases.",
        },
        "Chapter 2: Stacks, Queues & Hashing": {
            "Novice": "LIFO vs FIFO, push/pop/enqueue/dequeue, hash maps.",
            "Intermediate": "Implementing stacks/queues, hash collisions, load factor.",
            "Expert": "Open addressing vs chaining, deque internals, O(1) design.",
        },
        "Chapter 3: Sorting & Searching": {
            "Novice": "Linear vs binary search, the idea of sorting.",
            "Intermediate": "Big-O of common sorts, binary search preconditions.",
            "Expert": "Stability, in-place trade-offs, comparison-sort lower bounds.",
        },
    },
    "Intro to Data Science": {
        "Chapter 1: Data & Statistics Basics": {
            "Novice": "Mean/median/mode, categorical vs numerical data.",
            "Intermediate": "Variance/std dev, distributions, interpreting correlation.",
            "Expert": "Sampling bias, confidence intervals, correlation vs causation.",
        },
        "Chapter 2: Data Wrangling with Pandas": {
            "Novice": "DataFrames, selecting rows/columns, reading a CSV.",
            "Intermediate": "Filtering, groupby/aggregation, missing values.",
            "Expert": "Merges/joins, pivot/melt reshaping, vectorisation vs apply.",
        },
        "Chapter 3: Visualization & Intro to ML": {
            "Novice": "Choosing the right chart, reading a plot.",
            "Intermediate": "Train/test split, supervised learning, over/under-fitting.",
            "Expert": "Bias-variance, precision/recall/ROC, cross-validation.",
        },
    },
    "Mathematics": {
        "Chapter 1: Arithmetic & Fractions": {
            "Novice": "Order of operations, basic arithmetic, what a fraction is.",
            "Intermediate": "Fractions with unlike denominators, percentages, ratios.",
            "Expert": "Multi-step word problems, fraction/decimal/percent conversion.",
        },
        "Chapter 2: Algebra Basics": {
            "Novice": "Variables, evaluating expressions, one-step equations.",
            "Intermediate": "Linear equations, slope/intercept of a line.",
            "Expert": "Factoring quadratics, systems of equations, exponents.",
        },
        "Chapter 3: Geometry & Intro to Calculus": {
            "Novice": "Area/perimeter, angles, Pythagorean theorem.",
            "Intermediate": "Circle area/circumference, volume, coordinate geometry.",
            "Expert": "Limits, the derivative as a rate of change, tangent slope.",
        },
    },
}

SUBJECT_META = {
    "Basic Python Programming": ("🐍", "Variables, control flow, and functions."),
    "Data Structures & Algorithms": ("🧮", "Arrays, hashing, sorting, complexity."),
    "Intro to Data Science": ("📊", "Stats, pandas, and a first taste of ML."),
    "Mathematics": ("📐", "Arithmetic, algebra, geometry, calculus."),
}

# ---- Gamification constants ----
XP_PER_LEVEL = 200
XP_READ = 20
XP_CORRECT = 50
PROMOTION_THRESHOLD = 2  # consecutive correct to level up a tier
NUM_DIAGNOSTIC = 3

# Default model per backend.
OLLAMA_MODEL = "llama3"
# A larger model produces far more self-consistent quiz questions; this one is
# free on Groq. Override via LLM_MODEL if needed.
GROQ_MODEL = "llama-3.3-70b-versatile"
GROQ_BASE_URL = "https://api.groq.com/openai/v1"


def chapters_for(subject):
    return list(SUBJECTS.get(subject, {}).keys())


# =========================================================================== #
# LLM backend
# =========================================================================== #
def _config(key, default=None):
    try:
        if key in st.secrets:
            return st.secrets[key]
    except Exception:  # noqa: BLE001
        pass
    return os.environ.get(key, default)


def resolve_backend():
    api_key = _config("GROQ_API_KEY")
    forced = (_config("LLM_BACKEND") or "").strip().lower()
    use_groq = forced == "groq" or (forced != "ollama" and bool(api_key))
    if use_groq:
        return {"name": "groq", "model": _config("LLM_MODEL", GROQ_MODEL), "api_key": api_key}
    return {"name": "ollama", "model": _config("LLM_MODEL", OLLAMA_MODEL), "api_key": None}


def _messages(system_prompt, user_prompt):
    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]


def _ollama_call(messages, temperature, json_mode):
    if ollama is None:
        raise RuntimeError("The 'ollama' package is not installed.")
    kwargs = {"model": st.session_state.backend["model"], "messages": messages,
              "options": {"temperature": temperature}}
    if json_mode:
        kwargs["format"] = "json"
    return ollama.chat(**kwargs)["message"]["content"]


def _groq_call(messages, temperature, json_mode):
    from openai import OpenAI

    client = OpenAI(api_key=st.session_state.backend["api_key"], base_url=GROQ_BASE_URL)
    kwargs = {"model": st.session_state.backend["model"], "messages": messages,
              "temperature": temperature}
    if json_mode:
        kwargs["response_format"] = {"type": "json_object"}
    return client.chat.completions.create(**kwargs).choices[0].message.content


def _chat(system_prompt, user_prompt, temperature=0.6, json_mode=False, retries=2):
    call = _groq_call if st.session_state.backend["name"] == "groq" else _ollama_call
    messages = _messages(system_prompt, user_prompt)
    last_err = None
    for _ in range(retries + 1):
        content = call(messages, temperature, json_mode)
        if not json_mode:
            return content
        try:
            return json.loads(content)
        except (json.JSONDecodeError, TypeError) as exc:
            last_err = exc
    raise ValueError(f"Model did not return valid JSON after retries: {last_err}")


def _generate_mcq_once(subject, chapter, difficulty):
    """Single generation attempt with structural validation."""
    desc = SUBJECTS[subject][chapter][difficulty]
    system_prompt = (
        "You are an expert instructor writing one high-quality multiple-choice "
        "question. The option named by correct_option MUST be factually correct, "
        "and the explanation MUST justify that exact option (no contradictions). "
        "Respond ONLY with JSON — no markdown fences or extra prose."
    )
    user_prompt = f"""Create one {difficulty}-level multiple-choice question for "{chapter}" in a "{subject}" course.
Focus: {desc}

Return JSON EXACTLY like:
{{"question": "...", "options": {{"A": "...", "B": "...", "C": "...", "D": "..."}}, "correct_option": "A", "explanation": "why the correct answer is right"}}
correct_option MUST be one of A, B, C, D, and its option text must be the truly correct answer."""
    data = _chat(system_prompt, user_prompt, temperature=0.7, json_mode=True)
    if not all(k in data for k in ("question", "options", "correct_option", "explanation")):
        raise ValueError(f"Question JSON missing keys: {list(data)}")
    if not isinstance(data["options"], dict) or set(data["options"]) < set("ABCD"):
        raise ValueError("Options must include keys A, B, C, D.")
    if data["correct_option"] not in data["options"]:
        raise ValueError("correct_option does not match an option.")
    return data


def _verify_correct_option(q):
    """Independently re-derive the correct option (LLM-as-judge, temp 0).

    Returns the letter the grader believes is correct, or None on failure.
    """
    opts = "\n".join(f"{k}. {v}" for k, v in q["options"].items())
    system_prompt = (
        "You are a meticulous exam grader. Decide which single option is correct. "
        "Respond ONLY with JSON."
    )
    user_prompt = (
        f"Question: {q['question']}\nOptions:\n{opts}\n\n"
        'Return {"correct_option": "X"} where X is the letter (A-D) of the '
        "single correct option."
    )
    try:
        v = _chat(system_prompt, user_prompt, temperature=0.0, json_mode=True)
        letter = str(v.get("correct_option", "")).strip().upper()[:1]
        return letter if letter in q["options"] else None
    except Exception:  # noqa: BLE001 — verification is best-effort
        return None


def generate_mcq(subject, chapter, difficulty, attempts=2):
    """Generate a self-consistent MCQ.

    Generates, then has the model independently grade its own question. If the
    grader disagrees with the labelled answer, regenerate. As a last resort,
    trust the grader's verdict so the labelled answer is never self-contradictory.
    """
    last = None
    for _ in range(attempts):
        q = _generate_mcq_once(subject, chapter, difficulty)
        last = q
        verdict = _verify_correct_option(q)
        if verdict is None or verdict == q["correct_option"]:
            return q  # consistent (or unverifiable — accept as-is)
    # Disagreement persisted: trust the independent grader on the final attempt.
    verdict = _verify_correct_option(last)
    if verdict and verdict in last["options"]:
        last["correct_option"] = verdict
    return last


def generate_study_material(subject, chapter, difficulty):
    """Generate Markdown study notes tailored to the chapter and tier."""
    desc = SUBJECTS[subject][chapter][difficulty]
    system_prompt = (
        "You are an engaging tutor writing concise study notes in GitHub-flavored "
        "Markdown. Use a short intro, 3-5 bullet points, and a fenced code block or "
        "worked example where useful. Keep it under ~220 words. No preamble."
    )
    user_prompt = (
        f'Write {difficulty}-level study material for "{chapter}" in "{subject}". '
        f"Focus on: {desc}. End with one quick takeaway."
    )
    return _chat(system_prompt, user_prompt, temperature=0.5, json_mode=False)


def list_local_models():
    data = ollama.list()
    models = getattr(data, "models", None)
    if models is None and isinstance(data, dict):
        models = data.get("models", [])
    names = []
    for m in models or []:
        name = getattr(m, "model", None)
        if name is None and isinstance(m, dict):
            name = m.get("model") or m.get("name")
        if name:
            names.append(name)
    return names


def model_is_available(model, names):
    base = model.split(":")[0]
    return any(n == model or n.split(":")[0] == base for n in names)


def render_llm_error(exc):
    backend = st.session_state.backend
    if backend["name"] == "groq":
        st.error(
            "**Couldn't reach the Groq API.** Check `GROQ_API_KEY` is set and the "
            f"model `{backend['model']}` is valid / has quota.\n\nDetails: `{exc}`"
        )
    else:
        st.error(
            "**Couldn't reach the local model.**\n\n1. Start the server: `ollama serve`\n"
            f"2. Pull the model: `ollama pull {backend['model']}`\n\nDetails: `{exc}`"
        )


# =========================================================================== #
# Session state
# =========================================================================== #
def init_state():
    defaults = {
        "backend": resolve_backend(),
        "phase": "SUBJECT_SELECTION",
        "selected_subject": None,
        "current_chapter": None,
        "current_difficulty": "Novice",
        "baseline_skill": None,
        # gamification
        "xp": 0,
        "level": 1,
        "streak": 0,
        "consecutive_correct": 0,
        "badges": [],
        "chapters_completed": 0,
        "just_leveled": False,
        # diagnostic
        "diag_index": 0,
        "diag_correct": 0,
        "diag_question": None,
        # study / quiz
        "study_content": None,
        "study_read": False,
        "quiz_question": None,
        "quiz_result": None,
        "completed": False,
    }
    for key, value in defaults.items():
        st.session_state.setdefault(key, value)


def start_subject(subject):
    """Begin a fresh run for a subject, heading into the diagnostic."""
    st.session_state.selected_subject = subject
    st.session_state.current_chapter = chapters_for(subject)[0]
    st.session_state.current_difficulty = "Novice"
    st.session_state.baseline_skill = None
    st.session_state.diag_index = 0
    st.session_state.diag_correct = 0
    st.session_state.diag_question = None
    st.session_state.study_content = None
    st.session_state.study_read = False
    st.session_state.quiz_question = None
    st.session_state.quiz_result = None
    st.session_state.completed = False
    st.session_state.phase = "DIAGNOSTIC"


def back_to_selection():
    st.session_state.phase = "SUBJECT_SELECTION"
    st.session_state.selected_subject = None


# =========================================================================== #
# Gamification
# =========================================================================== #
def add_xp(amount):
    st.session_state.xp += amount
    new_level = 1 + st.session_state.xp // XP_PER_LEVEL
    if new_level > st.session_state.level:
        st.session_state.level = new_level
        st.session_state.just_leveled = True


def check_badges():
    """Unlock achievement titles; returns any newly unlocked this call."""
    s = st.session_state
    rules = [
        ("🎯 First Steps", s.xp > 0),
        ("🔥 On Fire", s.streak >= 3),
        ("⚡ Unstoppable", s.streak >= 5),
        ("🌟 Rising Star", s.level >= 2),
        ("👑 Scholar", s.level >= 5),
        ("🧠 Prodigy", s.baseline_skill == "Expert"),
        ("📘 Chapter Master", s.chapters_completed >= 1),
    ]
    newly = []
    for title, cond in rules:
        if cond and title not in s.badges:
            s.badges.append(title)
            newly.append(title)
    return newly


def _promote():
    chapters = chapters_for(st.session_state.selected_subject)
    tier_idx = TIERS.index(st.session_state.current_difficulty)
    if tier_idx < len(TIERS) - 1:
        st.session_state.current_difficulty = TIERS[tier_idx + 1]
        return f"🎉 Promoted to **{st.session_state.current_difficulty}** tier!"
    chap_idx = chapters.index(st.session_state.current_chapter)
    st.session_state.chapters_completed += 1
    if chap_idx < len(chapters) - 1:
        st.session_state.current_chapter = chapters[chap_idx + 1]
        st.session_state.current_difficulty = "Novice"
        return f"🏆 Chapter cleared! Advancing to **{st.session_state.current_chapter}**."
    st.session_state.completed = True
    return "🎓 Subject mastered — all chapters complete!"


def _demote():
    tier_idx = TIERS.index(st.session_state.current_difficulty)
    if tier_idx > 0:
        st.session_state.current_difficulty = TIERS[tier_idx - 1]
        return f"↩️ Difficulty eased to **{st.session_state.current_difficulty}** — reinforce the basics."
    return "💪 Holding at Novice — let's build a solid base."


def record_correct():
    add_xp(XP_CORRECT)
    st.session_state.streak += 1
    st.session_state.consecutive_correct += 1
    if st.session_state.consecutive_correct >= PROMOTION_THRESHOLD:
        st.session_state.consecutive_correct = 0
        return _promote()
    remaining = PROMOTION_THRESHOLD - st.session_state.consecutive_correct
    return f"✅ Correct! +{XP_CORRECT} XP · {remaining} more to advance."


def record_wrong():
    st.session_state.streak = 0
    st.session_state.consecutive_correct = 0
    return _demote()


# =========================================================================== #
# UI fragments
# =========================================================================== #
def render_sidebar_hud():
    s = st.session_state
    xp_in_level = s.xp % XP_PER_LEVEL
    pct = int(100 * xp_in_level / XP_PER_LEVEL)

    with st.sidebar:
        st.markdown(
            f"""
            <div class="hud-card">
              <div class="hud-title">⚡ Player · Lv {s.level}</div>
              <div class="xp-bar"><div class="xp-fill" style="width:{pct}%"></div></div>
              <div class="xp-text">{xp_in_level} / {XP_PER_LEVEL} XP · {s.xp} total</div>
              <div class="hud-row"><span class="k">🔥 Streak</span>
                  <span class="v">{s.streak}</span></div>
              <div class="hud-row"><span class="k">Subject</span>
                  <span class="v">{(s.selected_subject or '—')[:18]}</span></div>
              <div class="hud-row"><span class="k">Tier</span>
                  <span class="v">{s.baseline_skill or s.current_difficulty}</span></div>
            </div>
            """,
            unsafe_allow_html=True,
        )

        badge_html = (
            "".join(f'<span class="badge">{b}</span>' for b in s.badges)
            if s.badges else '<span class="badge-empty">No trophies yet — go earn some!</span>'
        )
        st.markdown(
            f"""
            <div class="hud-card">
              <div class="hud-title">🏆 Trophy Room</div>
              {badge_html}
            </div>
            """,
            unsafe_allow_html=True,
        )

        if s.selected_subject and st.button("🔁 Change Subject", use_container_width=True):
            back_to_selection()
            st.rerun()


def celebrate_levelups():
    """Show balloons + a banner when the player just leveled up."""
    if st.session_state.just_leveled:
        st.balloons()
        st.success(f"⚡ LEVEL UP! You reached **Level {st.session_state.level}**!")
        st.session_state.just_leveled = False
    for title in check_badges():
        st.toast(f"🏅 Badge unlocked: {title}")


def ensure_backend_ready():
    """Pre-flight check for the active backend. Returns True if good to go."""
    backend = st.session_state.backend
    if backend["name"] == "groq":
        if not backend["api_key"]:
            st.error("**No `GROQ_API_KEY` configured.** Add it to Streamlit secrets or env.")
            return False
        return True
    try:
        names = list_local_models()
    except Exception as exc:  # noqa: BLE001
        render_llm_error(exc)
        if st.button("Retry connection"):
            st.rerun()
        return False
    if not model_is_available(backend["model"], names):
        st.warning(
            f"Model **{backend['model']}** isn't pulled. Run "
            f"`ollama pull {backend['model']}` (have: {', '.join(names) or 'none'})."
        )
        if st.button("Retry"):
            st.rerun()
        return False
    return True


# =========================================================================== #
# Phase: SUBJECT SELECTION
# =========================================================================== #
def phase_subject_selection():
    st.title("🕹️ ADAPTIVE TUTOR")
    st.markdown("#### Choose your skill tree, challenger.")
    st.caption("Each subject runs a quick diagnostic, then adapts to your level as you play.")
    st.write("")

    subjects = list(SUBJECTS.keys())
    cols = st.columns(2)
    for i, subject in enumerate(subjects):
        icon, blurb = SUBJECT_META.get(subject, ("📚", ""))
        with cols[i % 2]:
            st.markdown(
                f"""
                <div class="subject-card">
                  <div class="title">{icon} {subject}</div>
                  <div class="blurb">{blurb}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )
            if st.button(f"▶ Start {subject.split()[0]}", key=f"pick_{i}",
                         use_container_width=True):
                start_subject(subject)
                st.rerun()
            st.write("")


# =========================================================================== #
# Phase: DIAGNOSTIC
# =========================================================================== #
def _finalize_diagnostic():
    correct = st.session_state.diag_correct
    baseline = "Novice" if correct <= 1 else "Intermediate" if correct == 2 else "Expert"
    st.session_state.baseline_skill = baseline
    st.session_state.current_difficulty = baseline
    st.session_state.phase = "STUDY"
    st.session_state.study_content = None
    st.session_state.study_read = False
    check_badges()  # 🧠 Prodigy if Expert


def phase_diagnostic():
    s = st.session_state
    st.title("🧪 DIAGNOSTIC SCAN")
    st.caption(f"{s.selected_subject} · calibrating your starting tier")

    if s.diag_index >= NUM_DIAGNOSTIC:
        _finalize_diagnostic()
        st.rerun()
        return

    # One probe per tier: Novice → Intermediate → Expert.
    probe_tier = TIERS[s.diag_index]
    if s.diag_question is None:
        with st.spinner(f"Generating probe {s.diag_index + 1}/{NUM_DIAGNOSTIC}…"):
            try:
                s.diag_question = generate_mcq(
                    s.selected_subject, s.current_chapter, probe_tier
                )
            except Exception as exc:  # noqa: BLE001
                render_llm_error(exc)
                if st.button("Try again"):
                    st.rerun()
                return

    q = s.diag_question
    st.progress(s.diag_index / NUM_DIAGNOSTIC, text=f"Probe {s.diag_index + 1} of {NUM_DIAGNOSTIC}")
    with st.container(border=True):
        st.markdown(f"**[{probe_tier}]** {q['question']}")
        choice = st.radio(
            "Your answer:", list("ABCD"),
            format_func=lambda k: f"{k}.  {q['options'][k]}",
            index=None, key=f"diag_{s.diag_index}",
        )
        if st.button("Submit ▶", type="primary"):
            if choice is None:
                st.warning("Pick an option.")
            else:
                if choice == q["correct_option"]:
                    s.diag_correct += 1
                s.diag_index += 1
                s.diag_question = None
                st.rerun()


# =========================================================================== #
# Phase: STUDY
# =========================================================================== #
def phase_study():
    s = st.session_state
    if s.completed:
        return phase_complete()

    st.title("📖 STUDY MODE")
    st.caption(f"{s.selected_subject} · {s.current_chapter} · **{s.current_difficulty}**")
    if s.baseline_skill:
        st.markdown(f"Diagnostic locked your baseline at **{s.baseline_skill}**. 🧠")

    if s.study_content is None:
        with st.spinner("Compiling your custom briefing…"):
            try:
                s.study_content = generate_study_material(
                    s.selected_subject, s.current_chapter, s.current_difficulty
                )
            except Exception as exc:  # noqa: BLE001
                render_llm_error(exc)
                if st.button("Try again"):
                    st.rerun()
                return

    with st.container(border=True):
        st.markdown(s.study_content)

    col1, col2 = st.columns(2)
    with col1:
        if not s.study_read:
            if st.button(f"📗 Read Material (+{XP_READ} XP)", type="primary",
                         use_container_width=True):
                add_xp(XP_READ)
                s.study_read = True
                st.rerun()
        else:
            st.success(f"✓ +{XP_READ} XP claimed")
    with col2:
        if s.study_read and st.button("⚔️ Take the Quiz →", type="primary",
                                      use_container_width=True):
            s.phase = "QUIZ"
            s.quiz_question = None
            s.quiz_result = None
            st.rerun()

    celebrate_levelups()


# =========================================================================== #
# Phase: QUIZ
# =========================================================================== #
def phase_quiz():
    s = st.session_state
    if s.completed:
        return phase_complete()

    st.title("⚔️ QUIZ ARENA")
    st.caption(f"{s.selected_subject} · {s.current_chapter} · **{s.current_difficulty}**")

    if s.quiz_question is None:
        with st.spinner("Summoning a challenge…"):
            try:
                s.quiz_question = generate_mcq(
                    s.selected_subject, s.current_chapter, s.current_difficulty
                )
            except Exception as exc:  # noqa: BLE001
                render_llm_error(exc)
                if st.button("Try again"):
                    st.rerun()
                return

    q = s.quiz_question

    # Phase 1: awaiting answer.
    if s.quiz_result is None:
        with st.container(border=True):
            st.markdown(f"### {q['question']}")
            choice = st.radio(
                "Lock in your answer:", list("ABCD"),
                format_func=lambda k: f"{k}.  {q['options'][k]}",
                index=None, key="quiz_choice",
            )
            if st.button("🎯 Submit Answer", type="primary"):
                if choice is None:
                    st.warning("Pick an option.")
                else:
                    correct = choice == q["correct_option"]
                    transition = record_correct() if correct else record_wrong()
                    s.quiz_result = {
                        "correct": correct,
                        "your_answer": f"{choice}. {q['options'][choice]}",
                        "correct_answer": f"{q['correct_option']}. {q['options'][q['correct_option']]}",
                        "explanation": q["explanation"],
                        "transition": transition,
                    }
                    st.rerun()
        return

    # Phase 2: feedback.
    r = s.quiz_result
    with st.container(border=True):
        if r["correct"]:
            st.success("✅ CORRECT!")
            st.balloons()
        else:
            st.error("❌ NOT QUITE")
            st.markdown(f"**Your answer:** {r['your_answer']}")
            st.markdown(f"**Correct answer:** {r['correct_answer']}")
        st.info(f"**Explanation:** {r['explanation']}")
        st.markdown(f"*{r['transition']}*")

    celebrate_levelups()

    if st.button("Continue →", type="primary"):
        s.study_content = None
        s.study_read = False
        s.quiz_question = None
        s.quiz_result = None
        s.phase = "STUDY"
        st.rerun()


# =========================================================================== #
# Phase: COMPLETE
# =========================================================================== #
def phase_complete():
    s = st.session_state
    st.balloons()
    st.title("🎓 SUBJECT MASTERED")
    with st.container(border=True):
        st.markdown(f"### You conquered **{s.selected_subject}**!")
        st.markdown(
            f"- **Level:** {s.level}\n"
            f"- **Total XP:** {s.xp}\n"
            f"- **Badges:** {len(s.badges)}\n"
            f"- **Chapters cleared:** {s.chapters_completed}"
        )
    if st.button("🕹️ Pick another subject", type="primary"):
        back_to_selection()
        st.rerun()


# =========================================================================== #
# Main
# =========================================================================== #
st.set_page_config(page_title="Adaptive Tutor Arcade", page_icon="🕹️", layout="centered")
st.markdown(CUSTOM_CSS, unsafe_allow_html=True)
init_state()

# Sidebar HUD is always visible once a subject is chosen.
if st.session_state.selected_subject:
    render_sidebar_hud()

# Backend must be reachable before any generation phase.
if st.session_state.phase != "SUBJECT_SELECTION" and not ensure_backend_ready():
    st.stop()

PHASES = {
    "SUBJECT_SELECTION": phase_subject_selection,
    "DIAGNOSTIC": phase_diagnostic,
    "STUDY": phase_study,
    "QUIZ": phase_quiz,
}
PHASES.get(st.session_state.phase, phase_subject_selection)()
